"""Stable symbol-level public API for the combat simulator package."""

from .simulation.actions import CombatAction
from .agents.agent_io import load_agent, save_agent
from .agents.baselines import (
    EvaluationSnapshot,
    EvaluationStats,
    QLearningAgent,
    TrainingResult,
    choose_heuristic_action,
    choose_random_action,
    evaluate_policy,
    train_q_learning,
)
from .analysis.bruteforce import (
    BruteForceProgress,
    BruteForceResult,
    OracleStep,
    brute_force_combat,
)
from .simulation.card import (
    BashCard,
    Card,
    CardSpec,
    DefendCard,
    SlimedCard,
    StrikeCard,
    create_starter_deck,
    get_card_spec,
)
from .simulation.core import CombatEnv
from .agents.dqn import (
    DQNAgent,
    DQNTrainingResult,
    DoubleDQNAgent,
    DuelingDoubleDQNAgent,
    ReplayBuffer,
    ReplayTransition,
    train_double_dqn,
    train_dqn,
    train_dueling_double_dqn,
)
from .simulation.encoding import ObservationEncoder
from .simulation.env_factory import (
    CombatEnvFactory,
    SUPPORTED_ENCOUNTERS,
    SUPPORTED_FIXED_ENCOUNTERS,
    SUPPORTED_TRAINING_ENCOUNTER_SETS,
)
from .simulation.enemy import (
    Enemy,
    FuzzyWurmCrawler,
    Intent,
    LeafSlimeMedium,
    LeafSlimeSmall,
    Mawler,
    Nibbit,
    ShrinkerBeetle,
    SimpleEnemy,
    TwigSlimeMedium,
    TwigSlimeSmall,
    build_overgrowth_easy_encounter,
    build_overgrowth_hard_v1_encounter,
    build_overgrowth_mawler_encounter,
    build_overgrowth_nibbits_encounter,
    build_overgrowth_shrinker_fuzzy_encounter,
    build_overgrowth_slimes_encounter,
    sample_overgrowth_first_three_encounter_builders,
)
from .simulation.gym_env import GymCombatEnv
from .simulation.player import Player
from .agents.ppo import PPOAgent, PPOTrainingResult, train_masked_ppo
from .analysis.oracle import (
    OracleActionEvaluation,
    OracleDecisionAnalysis,
    OraclePolicyAnalysis,
    analyze_episode_trace_with_oracle,
    analyze_oracle_decision,
)
from .analysis.uncertainty import (
    InformationAwareActionEvaluation,
    InformationAwareDecisionAnalysis,
    InformationAwarePolicyAnalysis,
    analyze_episode_trace_with_uncertainty,
    analyze_information_aware_decision,
    sample_hidden_combat_states,
)
from .simulation.status import (
    SHRINK,
    STATUS_STACK_SCALE,
    SUPPORTED_STATUS_NAMES,
    StatusCollection,
    VULNERABLE,
)
from .simulation.trajectory import EpisodeSummary, TransitionRecord
from .analysis.trace import TraceAnalysisReport, TraceFinding, analyze_episode_trace
from .analysis.watch import (
    EpisodeTrace,
    StepTrace,
    load_episode_trace,
    save_episode_trace,
    trace_policy_episode,
)

__all__ = [
    "BashCard",
    "BruteForceProgress",
    "BruteForceResult",
    "Card",
    "CardSpec",
    "CombatAction",
    "CombatEnv",
    "CombatEnvFactory",
    "DefendCard",
    "DQNAgent",
    "DQNTrainingResult",
    "DoubleDQNAgent",
    "DuelingDoubleDQNAgent",
    "Enemy",
    "EvaluationSnapshot",
    "EvaluationStats",
    "EpisodeTrace",
    "EpisodeSummary",
    "FuzzyWurmCrawler",
    "GymCombatEnv",
    "InformationAwareActionEvaluation",
    "InformationAwareDecisionAnalysis",
    "InformationAwarePolicyAnalysis",
    "Intent",
    "LeafSlimeMedium",
    "LeafSlimeSmall",
    "Mawler",
    "Nibbit",
    "ObservationEncoder",
    "OracleActionEvaluation",
    "OracleDecisionAnalysis",
    "OraclePolicyAnalysis",
    "OracleStep",
    "Player",
    "PPOAgent",
    "PPOTrainingResult",
    "QLearningAgent",
    "ReplayBuffer",
    "ReplayTransition",
    "ShrinkerBeetle",
    "SimpleEnemy",
    "SlimedCard",
    "SHRINK",
    "StepTrace",
    "StatusCollection",
    "STATUS_STACK_SCALE",
    "StrikeCard",
    "SUPPORTED_ENCOUNTERS",
    "SUPPORTED_FIXED_ENCOUNTERS",
    "SUPPORTED_TRAINING_ENCOUNTER_SETS",
    "SUPPORTED_STATUS_NAMES",
    "TraceAnalysisReport",
    "TraceFinding",
    "TrainingResult",
    "TransitionRecord",
    "TwigSlimeMedium",
    "TwigSlimeSmall",
    "VULNERABLE",
    "build_overgrowth_easy_encounter",
    "build_overgrowth_hard_v1_encounter",
    "build_overgrowth_mawler_encounter",
    "build_overgrowth_nibbits_encounter",
    "build_overgrowth_shrinker_fuzzy_encounter",
    "build_overgrowth_slimes_encounter",
    "brute_force_combat",
    "choose_heuristic_action",
    "choose_random_action",
    "create_starter_deck",
    "evaluate_policy",
    "get_card_spec",
    "load_agent",
    "load_episode_trace",
    "sample_overgrowth_first_three_encounter_builders",
    "sample_hidden_combat_states",
    "save_agent",
    "save_episode_trace",
    "analyze_episode_trace",
    "analyze_episode_trace_with_oracle",
    "analyze_episode_trace_with_uncertainty",
    "analyze_information_aware_decision",
    "analyze_oracle_decision",
    "trace_policy_episode",
    "train_double_dqn",
    "train_dqn",
    "train_dueling_double_dqn",
    "train_masked_ppo",
    "train_q_learning",
]
