"""Exclusive solo relic definitions; behavior lives in character_hooks."""

def definitions(relic_type):
    return {
        'helical_dart': relic_type('helical_dart', rarity='rare'),
        'ninja_scroll': relic_type('ninja_scroll', rarity='shop'),
        'paper_krane': relic_type('paper_krane', rarity='rare'),
        'ring_of_the_snake': relic_type('ring_of_the_snake', rarity='starter'),
        'snecko_skull': relic_type('snecko_skull', rarity='common'),
        'tingsha': relic_type('tingsha', rarity='uncommon'),
        'tough_bandages': relic_type('tough_bandages', rarity='rare'),
        'twisted_funnel': relic_type('twisted_funnel', rarity='uncommon'),
        'divine_right': relic_type('divine_right', rarity='starter'),
        'fencing_manual': relic_type('fencing_manual', rarity='common'),
        'galactic_dust': relic_type('galactic_dust', rarity='uncommon', counter_limit=9),
        'lunar_pastry': relic_type('lunar_pastry', rarity='rare'),
        'mini_regent': relic_type('mini_regent', rarity='rare'),
        'orange_dough': relic_type('orange_dough', rarity='rare'),
        'regalite': relic_type('regalite', rarity='uncommon'),
        'vitruvian_minion': relic_type('vitruvian_minion', rarity='shop'),
        'big_hat': relic_type('big_hat', rarity='rare'),
        'bone_flute': relic_type('bone_flute', rarity='common'),
        'book_repair_knife': relic_type('book_repair_knife', rarity='uncommon'),
        'bookmark': relic_type('bookmark', rarity='rare'),
        'bound_phylactery': relic_type('bound_phylactery', rarity='starter'),
        'funerary_mask': relic_type('funerary_mask', rarity='uncommon'),
        'ivory_tile': relic_type('ivory_tile', rarity='rare'),
        'undying_sigil': relic_type('undying_sigil', rarity='shop'),
        'cracked_core': relic_type('cracked_core', rarity='starter'),
        'data_disk': relic_type('data_disk', rarity='common'),
        'emotion_chip': relic_type('emotion_chip', rarity='rare'),
        'gold_plated_cables': relic_type('gold_plated_cables', rarity='uncommon'),
        'power_cell': relic_type('power_cell', rarity='rare'),
        'metronome': relic_type('metronome', rarity='rare'),
        'runic_capacitor': relic_type('runic_capacitor', rarity='shop'),
        'symbiotic_virus': relic_type('symbiotic_virus', rarity='uncommon'),
        'ring_of_the_drake': relic_type('ring_of_the_drake', rarity="starter"),
        'divine_destiny': relic_type('divine_destiny', rarity="starter"),
        'phylactery_unbound': relic_type('phylactery_unbound', rarity="starter"),
        'infused_core': relic_type('infused_core', rarity="starter"),
    }
