"""Pinned all-unlocked solo foreign pools in native character/declaration order."""

FAMILIES = ("silent", "regent", "necrobinder", "defect")

ORDINARY = {
    "silent": (
        'abrasive',
        'accelerant',
        'accuracy',
        'acrobatics',
        'adrenaline',
        'afterimage',
        'anticipate',
        'assassinate',
        'backflip',
        'backstab',
        'blade_of_ink',
        'blade_dance',
        'blur',
        'bouncing_flask',
        'bubble_bubble',
        'bullet_time',
        'burst',
        'calculated_gamble',
        'cloak_and_dagger',
        'corrosive_wave',
        'dagger_spray',
        'dagger_throw',
        'dash',
        'deadly_poison',
        'deflect',
        'dodge_and_roll',
        'echoing_slash',
        'envenom',
        'escape_plan',
        'expertise',
        'expose',
        'fan_of_knives',
        'finisher',
        'flechettes',
        'flick_flack',
        'scare',
        'footwork',
        'grand_finale',
        'hand_trick',
        'haze',
        'hidden_daggers',
        'infinite_blades',
        'knife_trap',
        'leading_strike',
        'leg_sweep',
        'malaise',
        'master_planner',
        'memento_mori',
        'mirage',
        'murder',
        'nightmare',
        'noxious_fumes',
        'outbreak',
        'phantom_blades',
        'piercing_wail',
        'pinpoint',
        'poisoned_stab',
        'pounce',
        'precise_cut',
        'predator',
        'prepared',
        'reflex',
        'ricochet',
        'serpent_form',
        'shadow_step',
        'shadowmeld',
        'skewer',
        'slice',
        'snakebite',
        'speedster',
        'storm_of_steel',
        'strangle',
        'sucker_punch',
        'tactician',
        'the_hunt',
        'tools_of_the_trade',
        'tracking',
        'untouchable',
        'up_my_sleeve',
        'well_laid_plans',
    ),
    "regent": (
        'alignment',
        'arsenal',
        'astral_pulse',
        'beat_into_shape',
        'begone',
        'big_bang',
        'black_hole',
        'bombardment',
        'bulwark',
        'bundle_of_joy',
        'celestial_might',
        'charge',
        'child_of_the_stars',
        'cloak_of_stars',
        'collision_course',
        'comet',
        'conqueror',
        'convergence',
        'cosmic_indifference',
        'crash_landing',
        'crescent_spear',
        'crush_under',
        'decisions_decisions',
        'devastate',
        'dying_star',
        'foregone_conclusion',
        'furnace',
        'gamma_blast',
        'gather_light',
        'genesis',
        'glimmer',
        'glitterstream',
        'glow',
        'guards',
        'guiding_star',
        'heavenly_drill',
        'hegemony',
        'heirloom_hammer',
        'hidden_cache',
        'i_am_invincible',
        'kingly_kick',
        'kingly_punch',
        'knockout_blow',
        'know_thy_place',
        'lunar_blast',
        'make_it_so',
        'manifest_authority',
        'monarchs_gaze',
        'monologue',
        'neutron_aegis',
        'orbit',
        'pale_blue_dot',
        'parry',
        'particle_wall',
        'patter',
        'photon_cut',
        'pillar_of_creation',
        'prophesize',
        'quasar',
        'radiate',
        'refine_blade',
        'reflect',
        'resonance',
        'royal_gamble',
        'royalties',
        'seeking_edge',
        'seven_stars',
        'shining_strike',
        'solar_strike',
        'spectrum_shift',
        'spoils_of_battle',
        'stardust',
        'summon_forth',
        'supermassive',
        'sword_sage',
        'terraforming',
        'the_smith',
        'tyranny',
        'void_form',
        'wrought_in_war',
    ),
    "necrobinder": (
        'afterlife',
        'banshees_cry',
        'blight_strike',
        'bone_shards',
        'borrowed_time',
        'bury',
        'calcify',
        'call_of_the_void',
        'capture_spirit',
        'cleanse',
        'countdown',
        'danse_macabre',
        'death_march',
        'deathbringer',
        'deaths_door',
        'debilitate',
        'defile',
        'defy',
        'delay',
        'demesne',
        'devour_life',
        'dirge',
        'drain_power',
        'dredge',
        'eidolon',
        'end_of_days',
        'enfeebling_touch',
        'eradicate',
        'fear',
        'fetch',
        'flatten',
        'friendship',
        'grave_warden',
        'graveblast',
        'hang',
        'haunt',
        'high_five',
        'invoke',
        'lethality',
        'melancholy',
        'misery',
        'necro_mastery',
        'negative_pulse',
        'neurosurge',
        'no_escape',
        'oblivion',
        'pagestorm',
        'parse',
        'poke',
        'pull_aggro',
        'pull_from_below',
        'putrefy',
        'rattle',
        'reanimate',
        'reap',
        'reaper_form',
        'reave',
        'right_hand_hand',
        'sacrifice',
        'scourge',
        'sculpting_strike',
        'seance',
        'sentry_mode',
        'severance',
        'shared_fate',
        'shroud',
        'sic_em',
        'sleight_of_flesh',
        'snap',
        'soul_storm',
        'sow',
        'spirit_of_ash',
        'spur',
        'squeeze',
        'the_scythe',
        'times_up',
        'transfigure',
        'undeath',
        'veilpiercer',
        'wisp',
    ),
    "defect": (
        'adaptive_strike',
        'all_for_one',
        'ball_lightning',
        'barrage',
        'beam_cell',
        'boost_away',
        'boot_sequence',
        'buffer',
        'bulk_up',
        'capacitor',
        'chaos',
        'charge_battery',
        'chill',
        'claw',
        'cold_snap',
        'compact',
        'compile_driver',
        'consuming_shadow',
        'coolant',
        'coolheaded',
        'creative_ai',
        'darkness',
        'defragment',
        'double_energy',
        'echo_form',
        'feral',
        'fight_through',
        'flak_cannon',
        'focused_strike',
        'ftl',
        'fusion',
        'genetic_algorithm',
        'glacier',
        'glasswork',
        'go_for_the_eyes',
        'gunk_up',
        'hailstorm',
        'helix_drill',
        'hologram',
        'hotfix',
        'hyperbeam',
        'ice_lance',
        'iteration',
        'leap',
        'lightning_rod',
        'loop',
        'machine_learning',
        'meteor_strike',
        'modded',
        'momentum_strike',
        'multi_cast',
        'null',
        'overclock',
        'rainbow',
        'reboot',
        'refract',
        'rocket_punch',
        'scavenge',
        'scrape',
        'shadow_shield',
        'shatter',
        'signal_boost',
        'skim',
        'smokestack',
        'spinner',
        'storm',
        'subroutine',
        'sunder',
        'supercritical',
        'sweeping_beam',
        'synchronize',
        'synthesis',
        'tempest',
        'tesla_coil',
        'thunder',
        'trash_to_treasure',
        'turbo',
        'uproar',
        'voltaic',
        'white_noise',
    ),
}

def complete(cards):
    definitions = {d.definition_id: d for d in cards.definitions}
    return all(name in definitions and definitions[name].pool == family
               and definitions[name].rarity in ('common', 'uncommon', 'rare')
               for family, names in ORDINARY.items() for name in names)


def splash_pool(cards):
    """A catalog represents installed unlock families; never sort family names."""
    from game.headless.generation.combat import card_pool
    families = [f for f in FAMILIES if any(d.pool == f for d in cards.definitions)]
    if not families:
        return card_pool(cards, 'ironclad', 'attack')
    result = []
    for family in families:
        rank = {name: i for i, name in enumerate(ORDINARY[family])}
        result.extend(sorted(card_pool(cards, family, 'attack'), key=lambda d: rank.get(d.definition_id, len(rank))))
    return result


def kaleidoscope(state, cards, source):
    """Two groups are fully created before either manually supplied reward populates."""
    from game.headless.generation.odds import card_offers
    from game.headless.relics.rewards import decorate
    groups = []
    for _ in range(2):
        families = sorted(FAMILIES)
        state.rng.shuffle('relic.foreign_pools', families)
        definitions, modifiers = [], {}
        for family in families[:3]:
            names, upgraded = card_offers(state, cards, ORDINARY[family], 1, mode='base')
            definitions.extend(names)
            modifiers.update(decorate(state, cards, names, card_reward=False, upgraded=upgraded))
        groups.append((definitions, modifiers))
    for definitions, modifiers in groups:
        modifiers = decorate(state, cards, definitions, card_reward=True, modifiers=modifiers)
        state.relic_work.append(dict(source=source, kind='card_reward',
            offers=[dict(definition_id=name, **modifiers[name]) for name in definitions]))
