<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PathMap>$(MSBuildThisFileDirectory)=/_/item_wire_v1/</PathMap>
    <RestoreIgnoreFailedSources>false</RestoreIgnoreFailedSources>
  </PropertyGroup>
</Project>
