<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <AnalysisLevel>9.0</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PathMap>$(MSBuildThisFileDirectory)=/_/item_v1/</PathMap>
    <PathMap Condition="'$(NuGetPackageRoot)' != ''">$(PathMap),$(NuGetPackageRoot)=/_/packages/</PathMap>
    <PathMap Condition="'$(STS2GameDataDir)' != ''">$(PathMap),$(STS2GameDataDir)=/_/game/</PathMap>
  </PropertyGroup>
</Project>
