<Project>
  <PropertyGroup>
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <InformationalVersion>1.0.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PathMap>$(MSBuildThisFileDirectory)..=/_/successors/</PathMap>
    <PathMap Condition="'$(STS2GameDataDir)' != ''">$(PathMap),$(STS2GameDataDir)=/_/game/</PathMap>
    <RestoreIgnoreFailedSources>false</RestoreIgnoreFailedSources>
  </PropertyGroup>
</Project>
