namespace Sts2AgentBridge.Successors.GenericEventReleaseV3;

// Closed diagnostic history vocabulary; values never authorize an action.
public enum GenericEventDiagnosticCode
{
    NotCaptured = 0,
    ParentReady = 1,
    ParentUnavailable = 2,
    ParentWaiting = 3,
    PendingBindingFailed = 4,
    PendingOwnership = 5,
    PendingContext = 6,
    PendingTaskFailed = 7,
    PendingChosenEntry = 8,
    PendingChosenTask = 9,
    PendingChosenCompletion = 10,
    PendingRequestTask = 11,
    PendingScreen = 12,
    PendingSelectorlessRequest = 13,
    PendingOverlay = 14,
    PendingDeck = 15,
    PendingOffers = 16,
    PendingProceed = 17,
    PrepareBinding = 18,
    PrepareScreen = 19,
    PrepareExternalSelector = 20,
    PrepareDeck = 21,
    PrepareForeground = 22,
    PrepareFamily = 23,
    PrepareGridNode = 24,
    PrepareGridState = 25,
    PrepareHolders = 26,
    PrepareCandidates = 27,
    PrepareGeometry = 28,
    PreparePreviewNodes = 29,
    PreparePreviewState = 30,
    PrepareConfirm = 31,
    ChildReady = 32,
    MapReady = 33,
    CaptureDisposed = 34,
    CaptureException = 35,
    DiagnosticUnavailable = 36,
}
