"""Public base relic rules for learning, not an executable effect simulator.

Each row has a shared trigger/effect and typed operands or conditions. Amounts
describe the unmodified rule, never a forecast or private instance state. Rules
are deliberately partial; comments bind groups to the authoritative engine code.
The catalog freezes these immutable rows into each new model's feature identity.
"""
from types import MappingProxyType


def _rule(trigger, kind, amount=None, **conditions):
    values = dict(trigger=trigger, kind=kind, **conditions)
    if amount is not None:
        values['amount'] = amount
    return tuple(sorted(values.items()))


def _pickup_selection(kind, minimum, maximum, **conditions):
    return _rule('pickup', kind, source='deck', selection='player',
                 selection_minimum=minimum, selection_maximum=maximum,
                 counts_clipped_to_eligible=True, **conditions)


RELIC_RULES = MappingProxyType({
    # relics/turns.py: combat entry, turn start, draw and end-turn hooks.
    'anchor': (_rule('combat_start', 'block', 10),),
    'vajra': (_rule('combat_start', 'strength', 1),),
    'oddly_smooth_stone': (_rule('combat_start', 'dexterity', 1),),
    'gorget': (_rule('combat_start', 'plating', 4),),
    'bronze_scales': (_rule('combat_start', 'thorns', 3),),
    'girya': (_rule('combat_start', 'strength', amount_source='display_counter', maximum=3),),
    'sling_of_courage': (_rule('combat_start', 'strength', 2, room_kind='elite'),),
    'ember_tea': (_rule('combat_start', 'strength', 2, uses=5, scope='run'),),
    'tea_of_discourtesy': (_rule('combat_start', 'generate_card', 2, card='dazed',
                               destination='draw_pile', position='random', uses=1, scope='run'),),
    'petrified_toad': (_rule('combat_start', 'generate_potion', 1, potion='potion_shaped_rock',
                            requires='empty_potion_slot', blocked_by='sozu'),),
    'stone_cracker': (_rule('combat_start', 'upgrade_card', 2, source='draw_pile',
                            selection='random_upgradable', duration='combat'),),
    'art_of_war': (_rule('turn_start', 'energy', 1, turn_min=2, previous_attacks_max=0),),
    'pocketwatch': (_rule('turn_start', 'draw', 3, turn_min=2, previous_plays_max=3),),
    'bag_of_preparation': (_rule('turn_start', 'draw', 2, turn=1),),
    'happy_flower': (_rule('turn_start', 'energy', 1, every=3, counter_scope='run'),),
    'venerable_tea_set': (_rule('turn_start', 'energy', 2, requires='entered_rest_since_last_trigger',
                               consume_charge=True),),
    'bread': (_rule('turn_start', 'energy', -2, turn=1, minimum_result=0),
              _rule('turn_start', 'energy', 1, turn_min=2)),
    'lantern': (_rule('turn_start', 'energy', 1, turn=1),),
    'very_hot_cocoa': (_rule('turn_start', 'energy', 4, turn=1),),
    'candelabra': (_rule('turn_start', 'energy', 2, turn=2),),
    'chandelier': (_rule('turn_start', 'energy', 3, turn=3),),
    'horn_cleat': (_rule('turn_start', 'block', 14, turn=2),),
    'captains_wheel': (_rule('turn_start', 'block', 18, turn=3),),
    'sparkling_rouge': (_rule('turn_start', 'strength', 1, turn=3),
                       _rule('turn_start', 'dexterity', 1, turn=3)),
    'bag_of_marbles': (_rule('turn_start', 'vulnerable', 1, turn=1, target='all_enemies'),),
    'red_mask': (_rule('turn_start', 'weak', 1, turn=1, target='all_enemies'),),
    'toolbox': (_rule('before_draw', 'choose_card', 1, turn=1, offers=3, pool='colorless',
                      optional=True, destination='hand'),),
    'booming_conch': (_rule('turn_start', 'draw', 2, turn=1, room_kind='elite'),
                     _rule('after_side_start', 'energy', 1, turn=1, room_kind='elite')),
    'bone_tea': (_rule('after_side_start', 'upgrade_card', target='hand', turn=1,
                       uses=1, scope='run', duration='combat'),),
    'akabeko': (_rule('after_side_start', 'vigor', 8, turn=1),),
    'brimstone': (_rule('after_side_start', 'strength', 2, target='player'),
                  _rule('after_side_start', 'strength', 1, target='all_enemies')),
    'mercury_hourglass': (_rule('after_draw', 'damage', 3, target='all_enemies', attack=False),),
    'blood_vial': (_rule('after_draw', 'heal', 2, turn=1),),
    'festive_popper': (_rule('after_draw', 'damage', 9, turn=1, target='all_enemies', attack=False),),
    'bellows': (_rule('after_draw', 'upgrade_card', turn=1, target='hand', duration='combat'),),
    'gambling_chip': (_rule('after_draw', 'discard_redraw', turn=1, target='selected_hand_cards',
                            optional=True, maximum='hand_size'),),
    'vexing_puzzlebox': (_rule('after_draw', 'generate_card', 1, turn=1, pool='character',
                              selection='random', destination='hand', energy_cost=0,
                              x_cost_unchanged=True, duration='combat'),),
    'orichalcum': (_rule('before_end', 'block', 6, requires='zero_block_at_end_turn_check'),),
    'cloak_clasp': (_rule('before_end', 'block', 1, per='card_in_hand'),),
    'ripple_basin': (_rule('before_end', 'block', 4, attacks_started_max=0),),
    'screaming_flagon': (_rule('before_end', 'damage', 20, requires='empty_hand',
                              target='all_enemies', attack=False),),
    'stone_calendar': (_rule('before_end', 'damage', 52, turn=7, target='all_enemies', attack=False),),
    'parrying_shield': (_rule('after_end', 'damage', 6, block_min=10, target='random_enemy', attack=False),),

    # relics/plays.py and damage.py: plays are cards, not individual hits.
    'nunchaku': (_rule('attack_card_played', 'energy', 1, every=10, counter_scope='run'),),
    'shuriken': (_rule('attack_card_played', 'strength', 1, every=3, counter_scope='turn'),),
    'kunai': (_rule('attack_card_played', 'dexterity', 1, every=3, counter_scope='turn'),),
    'ornamental_fan': (_rule('attack_card_played', 'block', 4, every=3, counter_scope='turn'),),
    'kusarigama': (_rule('attack_card_played', 'damage', 6, every=3, counter_scope='turn',
                         target='random_enemy', attack=False),),
    'tuning_fork': (_rule('skill_card_played', 'block', 7, every=10, counter_scope='run'),),
    'letter_opener': (_rule('skill_card_played', 'damage', 5, every=3, counter_scope='turn',
                           target='all_enemies', attack=False),),
    'intimidating_helmet': (_rule('before_card_play', 'block', 4, card_energy_value_min=2),),
    'pen_nib': (_rule('attack_card_play', 'attack_damage_multiplier', 2, every=10,
                     counter_scope='run', duration='whole_card_play'),),
    'game_piece': (_rule('power_card_played', 'draw', 1),),
    'permafrost': (_rule('power_card_played', 'block', 7, uses=1, scope='combat'),),
    'mummified_hand': (_rule('power_card_played', 'energy_cost_override', 0, selection='random',
                             target='positive_cost_card_in_hand', duration='turn'),),
    'rainbow_ring': (_rule('card_played', 'strength', 1, requires='attack_skill_and_power_played',
                           uses=1, scope='turn'),
                     _rule('card_played', 'dexterity', 1, requires='attack_skill_and_power_played',
                           uses=1, scope='turn')),
    'razor_tooth': (_rule('attack_or_skill_played', 'upgrade_card', target='played_card', duration='combat'),),
    'charons_ashes': (_rule('card_exhausted', 'damage', 3, target='all_enemies', attack=False),),
    'burning_sticks': (_rule('skill_card_exhausted', 'copy_card', 1, destination='hand', uses=1, scope='combat'),),
    'joss_paper': (_rule('card_exhausted', 'draw', 1, every=5, counter_scope='run',
                         ethereal_timing='after_end'),),
    'the_abacus': (_rule('shuffle', 'block', 6),),
    'unceasing_top': (_rule('hand_emptied', 'draw', 1, requires='player_side_not_ending'),),
    'ruined_helmet': (_rule('positive_strength_gain', 'amount_multiplier', 2, uses=1, scope='combat'),),
    'red_skull': (_rule('hp_changed', 'conditional_strength', 3, hp_percent_max=50, reversible=True),),
    'belt_buckle': (_rule('potion_inventory_changed', 'conditional_dexterity', 2,
                          requires='all_potion_slots_empty', reversible=True),),
    'tungsten_rod': (_rule('hp_loss', 'reduce_amount', 1, minimum_result=0),),
    'beating_remnant': (_rule('hp_loss', 'total_hp_loss_cap', 20, scope='turn'),),
    'lizard_tail': (_rule('would_die', 'revive_hp_percent', 50, minimum_hp=1, uses=1, scope='run'),),
    'centennial_puzzle': (_rule('positive_hp_loss', 'draw', 3, uses=1, scope='combat'),),
    'self_forming_clay': (_rule('positive_hp_loss', 'block', 3, timing='next_turn_start'),),
    'demon_tongue': (_rule('positive_hp_loss', 'heal', amount_source='hp_lost',
                          requires='player_side', uses=1, scope='turn'),),
    'strike_dummy': (_rule('card_attack_damage', 'add_damage', 3, card_family='strike'),),
    'miniature_cannon': (_rule('card_attack_damage', 'add_damage', 3, requires='upgraded_card'),),
    'mystic_lighter': (_rule('card_attack_damage', 'add_damage', 9, requires='enchanted_card'),),
    'vambrace': (_rule('positive_card_block_gain', 'amount_multiplier', 2,
                      uses=1, scope='combat', duration='whole_first_triggering_card_play'),),
    'unsettling_lamp': (_rule('positive_card_debuff', 'amount_multiplier', 2,
                             uses=1, scope='combat', duration='whole_first_triggering_card_play'),),

    # Shared core/powers/monster hooks, outside the relic dispatcher.
    'chemical_x': (_rule('x_card_play', 'add_x_effect_value', 2, resource='energy_or_stars'),),  # core/resolution.py
    'ghost_seed': (_rule('end_hand_cleanup', 'ethereal', card_family='strike_or_defend'),),  # core/resolution.py
    'ringing_triangle': (_rule('end_hand_cleanup', 'retain_hand', turn=1, excludes='ethereal_exhaust'),),
    'runic_pyramid': (_rule('end_hand_cleanup', 'retain_hand', excludes='ethereal_exhaust'),),
    'throwing_axe': (_rule('generate_card_play_count', 'extra_play', 1, uses=1, scope='combat'),),
    'pendulum': (_rule('after_draw', 'draw', 1, every=3, counter_scope='run'),),
    'ice_cream': (_rule('turn_start', 'retain_energy', turn_min=2),),  # powers/ironclad.py
    'sturdy_clamp': (_rule('turn_start', 'retain_block', maximum=10, turn_min=2),),
    'gremlin_horn': (_rule('enemy_death', 'energy', 1, requires='combat_continues'),  # monsters/base.py
                     _rule('enemy_death', 'draw', 1, requires='combat_continues')),
    'paper_phrog': (_rule('attack_vulnerable_enemy', 'vulnerability_bonus_percent_points', 25),),
    'reptile_trinket': (_rule('potion_finished', 'strength', 3, duration='until_end_turn'),),  # potions/combat.py
    'lava_lamp': (_rule('combat_card_reward', 'upgrade_offers',
                        requires='no_positive_blockable_hp_damage_in_combat'),),  # run/engine.py, relics/rewards.py

    # relics/character_hooks.py; before_side_start is once at combat setup.
    'divine_right': (_rule('combat_start', 'stars', 3),),
    'data_disk': (_rule('combat_start', 'focus', 1),),
    'bound_phylactery': (_rule('combat_start', 'summon_osty', 1),
                         _rule('turn_start', 'summon_osty', 1, turn_min=2)),
    'phylactery_unbound': (_rule('combat_start', 'summon_osty', 5),
                          _rule('after_side_start', 'summon_osty', 2)),
    'ring_of_the_snake': (_rule('turn_start', 'draw', 2, turn=1),),
    'ring_of_the_drake': (_rule('turn_start', 'draw', 2, turn_max=3),),
    'ninja_scroll': (_rule('before_draw', 'generate_card', 3, turn=1, card='shiv', destination='hand'),),
    'funerary_mask': (_rule('before_draw', 'generate_card', 3, turn=1, card='soul', destination='hand'),),
    'cracked_core': (_rule('combat_setup', 'channel_orb', 1, orb='lightning'),),
    'power_cell': (_rule('combat_setup', 'move_card', 2, source='draw_pile', destination='hand',
                         selection='random_zero_local_cost_non_x'),),
    'twisted_funnel': (_rule('combat_setup', 'poison', 4, target='all_enemies'),),
    'divine_destiny': (_rule('after_side_start', 'stars', 6, turn=1),),
    'fencing_manual': (_rule('after_side_start', 'forge', 10, turn=1),),
    'orange_dough': (_rule('after_side_start', 'generate_card', 2, turn=1, pool='colorless',
                           selection='random', destination='hand'),),
    'big_hat': (_rule('after_side_start', 'generate_card', 2, turn=1, selection='random_distinct_ethereal',
                     destination='hand'),),
    'runic_capacitor': (_rule('after_side_start', 'orb_slots', 3, turn=1),),
    'symbiotic_virus': (_rule('after_side_start', 'channel_orb', 1, orb='dark', turn=1),),
    'infused_core': (_rule('after_side_start', 'channel_orb', 3, orb='lightning', turn=1),),
    'emotion_chip': (_rule('after_draw', 'trigger_orb_passives', 1, target='all_orbs',
                           requires='positive_hp_loss_since_previous_turn_start'),),
    'helical_dart': (_rule('card_played', 'dexterity', 1, card='shiv', duration='until_end_turn'),),
    'ivory_tile': (_rule('card_played', 'energy', 1, card_energy_value_min=3),),
    'tingsha': (_rule('card_discarded', 'damage', 3, requires='player_side', target='random_enemy', attack=False),),
    'tough_bandages': (_rule('card_discarded', 'block', 3, requires='player_side'),),
    'lunar_pastry': (_rule('after_end', 'stars', 1),),
    'bookmark': (_rule('after_hand_flush', 'energy_cost_discount', 1,
                       target='random_positive_local_cost_non_x_card_in_hand', duration='until_played'),),
    'galactic_dust': (_rule('stars_spent', 'block', 10, every=10, counter_scope='run'),),
    'mini_regent': (_rule('stars_spent', 'strength', 1, uses=1, scope='turn'),),
    'regalite': (_rule('card_generated', 'block', 2),),
    'metronome': (_rule('orb_channeled', 'damage', 30, at_count=7, counter_scope='combat',
                        target='all_enemies', attack=False),),
    # Other character mechanics: core/player.py, monsters/base.py, core/osty.py,
    # powers/necrobinder.py, core/orbs.py, relics/damage.py.
    'paper_krane': (_rule('weak_enemy_attack', 'weak_damage_percent', 60, with_debilitate_percent=20),),
    'snecko_skull': (_rule('apply_poison', 'add_stacks', 1, target='enemy'),),
    'bone_flute': (_rule('osty_attack_finished', 'block', 2),),
    'book_repair_knife': (_rule('enemy_died_to_doom', 'heal', 3,
                               requires='non_minion_with_decimillipede_segment_fatal_restriction',
                               allows_illusion=True),),
    'undying_sigil': (_rule('enemy_attack', 'incoming_damage_percent', 50, requires='enemy_hp_at_most_doom'),),
    'gold_plated_cables': (_rule('orb_phase_passive', 'extra_trigger', 1, target='first_orb',
                                excludes='direct_passive_trigger'),),
    'vitruvian_minion': (_rule('card_attack_damage', 'amount_multiplier', 2, card_family='minion'),
                        _rule('positive_card_block_gain', 'amount_multiplier', 2, card_family='minion')),

    # relics/ancient_combat.py; negative effects also described where applicable.
    'blessed_antler': (_rule('turn_start', 'energy', 1),
                       _rule('before_draw', 'generate_card', 3, turn=1, card='dazed', destination='draw_pile', position='random')),
    'blood_soaked_rose': (_rule('turn_start', 'energy', 1),
                         _rule('pickup', 'add_card_to_deck', 1, card='enthralled')),  # ancient_pickups.py
    'ectoplasm': (_rule('turn_start', 'energy', 1), _rule('gold_gain', 'prevent_gold_gain')),
    'philosophers_stone': (_rule('turn_start', 'energy', 1),
                          _rule('combat_start', 'strength', 1, target='all_enemies')),
    'prismatic_gem': (_rule('turn_start', 'energy', 1),
                      _rule('normal_card_reward', 'add_all_character_pools')),
    'sozu': (_rule('turn_start', 'energy', 1), _rule('potion_gain', 'prevent_potion_gain')),
    'spiked_gauntlets': (_rule('turn_start', 'energy', 1),
                        _rule('power_card_cost', 'energy_cost_surcharge', 1)),  # powers/ironclad.py
    'velvet_choker': (_rule('turn_start', 'energy', 1),
                      _rule('card_play', 'play_limit', 6, scope='turn')),  # cards/curses.py
    'whispering_earring': (_rule('turn_start', 'energy', 1),
                           _rule('combat_preplay', 'autoplay_legal_hand_cards', maximum=13, turn=1, spends_resources=True)),
    'paels_flesh': (_rule('turn_start', 'energy', 1, turn_min=3),),
    'pumpkin_candle': (_rule('turn_start', 'energy', 1, requires='remaining_combat_charges'),),
    'fiddle': (_rule('turn_start', 'draw', 2),
               _rule('card_draw', 'prevent_extra_draw', requires='player_side', excludes='normal_hand_draw')),
    'snecko_eye': (_rule('turn_start', 'draw', 2), _rule('combat_start', 'confused', 1)),
    'paels_blood': (_rule('turn_start', 'draw', 1),),
    'delicate_frond': (_rule('combat_start', 'fill_potion_slots', selection='random', blocked_by='sozu'),),
    'iron_club': (_rule('card_played', 'draw', 1, every=4, counter_scope='run'),),
    'radiant_pearl': (_rule('before_draw', 'generate_card', 1, turn=1, card='luminesce', destination='hand'),),
    'jeweled_mask': (_rule('before_draw', 'move_card', 1, turn=1, source='draw_pile', destination='hand',
                          selection='random_power', energy_cost=0, duration='turn'),),
    'toasty_mittens': (_rule('before_draw', 'exhaust_card', 1, source='top_draw_pile',
                            first_turn_preference='non_innate'),
                       _rule('after_mittens_exhaust_attempt', 'strength', 1)),
    'sai': (_rule('after_side_start', 'block', 7),),
    'seal_of_gold': (_rule('after_side_start', 'energy', 1, gold_cost=5, gold_min=5),),
    'paels_tears': (_rule('turn_end_with_unspent_energy', 'energy', 2, timing='next_turn_after_side_start'),),
    'crossbow': (_rule('after_side_start', 'generate_card', 1, selection='random_attack',
                       destination='hand', energy_cost=0, duration='turn'),),
    'choices_paradox': (_rule('after_draw', 'choose_card', 1, turn=1, offers=5,
                              destination='hand', retain=True, duration='combat'),),
    'diamond_diadem': (_rule('enemy_attack', 'incoming_damage_percent', 50,
                             requires='ended_turn_with_at_most_two_card_plays'),),
    'paels_legion': (_rule('positive_card_block_gain', 'amount_multiplier', 2, cooldown_turns=2,
                           duration='whole_triggering_card_play'),),
    'music_box': (_rule('attack_card_played', 'copy_card', 1, destination='hand',
                        ethereal=True, uses=1, scope='turn'),),
    'brilliant_scarf': (_rule('card_cost', 'energy_cost_override', 0,
                             manual_plays_eq=4, card_location='hand_or_in_play', excludes_x_cost=True),),
    'paels_eye': (_rule('turn_end', 'exhaust_hand_and_take_extra_turn', requires='zero_manual_plays',
                        uses=1, scope='combat', first_turn_excluded_with='whispering_earring'),),
    'biiig_hug': (_rule('shuffle', 'generate_card', 1, card='soot', destination='draw_pile', position='random'),),

    # relics/event_content.py; fake items deliberately keep their own amounts.
    'big_mushroom': (_rule('turn_start', 'draw', -2, turn=1, minimum_result=0),),
    'pollinous_core': (_rule('turn_start', 'draw', 2, every=4, counter_scope='run'),),
    'fake_venerable_tea_set': (_rule('turn_start', 'energy', 1, requires='entered_rest_since_last_trigger',
                                    consume_charge=True),),
    'daughter_of_the_wind': (_rule('attack_card_played', 'block', 1),),
    'lost_wisp': (_rule('power_card_played', 'damage', 8, target='all_enemies', attack=False),),
    'forgotten_soul': (_rule('card_exhausted', 'damage', 1, target='random_enemy', attack=False),),
    'fake_happy_flower': (_rule('after_side_start', 'energy', 1, every=5, counter_scope='run'),),
    'royal_poison': (_rule('after_draw', 'hp_loss', 4, turn=1),),
    'fake_blood_vial': (_rule('after_draw', 'heal', 1, turn=1),),
    'mr_struggles': (_rule('after_draw', 'damage', amount_source='turn_number', target='all_enemies', attack=False),),
    'fake_orichalcum': (_rule('before_end', 'block', 3, requires='zero_block_at_end_turn_check'),),
    'history_course': (_rule('combat_preplay', 'autoplay_copy', 1, turn_min=2,
                             source='last_non_duplicate_attack_or_skill_of_previous_turn'),),
    'fake_anchor': (_rule('combat_start', 'block', 4),),  # relics/turns.py
    'fake_snecko_eye': (_rule('combat_start', 'confused', 1),),
    'fake_strike_dummy': (_rule('card_attack_damage', 'add_damage', 1, card_family='strike'),),
    'the_boot': (_rule('powered_attack_unblocked_damage', 'minimum_positive_damage', 5),),  # monsters/base.py
    'hand_drill': (_rule('break_enemy_block', 'vulnerable', 2,
                         damage_source='player_or_owned_pet'),),

    # Relic run effects directly implemented in relics/run_rules.py. These stay
    # useful for future full-run encoders without pretending to be combat buffs.
    'bowler_hat': (_rule('gold_gain', 'amount_percent', 125),),
    'dragon_fruit': (_rule('positive_gold_gain', 'max_hp', 1),),
    'molten_egg': (_rule('card_added_or_offered', 'upgrade_card', card_kind='attack'),),
    'toxic_egg': (_rule('card_added_or_offered', 'upgrade_card', card_kind='skill'),),
    'frozen_egg': (_rule('card_added_or_offered', 'upgrade_card', card_kind='power'),),
    'fresnel_lens': (_rule('card_added_or_offered', 'enchant_card', 2, enchantment='nimble'),),
    'darkstone_periapt': (_rule('curse_added', 'max_hp', 6),),
    'bing_bong': (_rule('non_clone_card_added', 'copy_card_to_deck', 1),),
    'book_of_five_rings': (_rule('card_added', 'heal', 20, every=5, counter_scope='run'),),
    'lucky_fysh': (_rule('card_added', 'gold', 15),),
    'maw_bank': (_rule('room_entered', 'gold', 12, requires='not_spent_gold_at_shop'),),
    'meal_ticket': (_rule('room_entered', 'heal', 15, room_kind='shop'),),
    'eternal_feather': (_rule('room_entered', 'heal', 3, room_kind='rest', per='five_deck_cards', rounding='floor'),),
    'pantograph': (_rule('room_entered', 'heal', 25, room_kind='boss'),),
    'planisphere': (_rule('room_entered', 'heal', 5, requires='unknown_map_node'),),
    'fishing_rod': (_rule('normal_combat_victory', 'upgrade_card', 1, every=3,
                         counter_scope='run', selection='random_upgradable'),),
    'chosen_cheese': (_rule('combat_victory', 'max_hp', 1),),
    'meat_on_the_bone': (_rule('combat_victory', 'heal', 12, hp_percent_max=50),),
    'war_hammer': (_rule('elite_victory', 'upgrade_card', 4, selection='random_upgradable'),),
    'lees_waffle': (_rule('pickup', 'heal_to_full'),),
    'potion_belt': (_rule('pickup', 'potion_slots', 2),),
    'war_paint': (_rule('pickup', 'upgrade_card', 2, card_kind='skill', selection='random_upgradable'),),
    'whetstone': (_rule('pickup', 'upgrade_card', 2, card_kind='attack', selection='random_upgradable'),),
    'dream_catcher': (_rule('rest', 'card_reward', 1),),
    'stone_humidifier': (_rule('rest', 'max_hp', 5),),
    'tiny_mailbox': (_rule('rest', 'potion_reward', 2),),
    # relics/rewards.py; only the available base offer rule, no hidden rolls.
    'prayer_wheel': (_rule('normal_combat_reward', 'extra_card_reward', 1),),
    'white_star': (_rule('elite_reward', 'extra_rare_card_reward', 1),),
    'black_star': (_rule('elite_reward', 'extra_relic_reward', 1),),
    'silver_crucible': (_rule('card_reward', 'upgrade_offers', uses=3, scope='run'),),
    'silken_tress': (_rule('card_reward', 'enchant_offers', 1, enchantment='glam', uses=1, scope='run'),),
    'wing_charm': (_rule('card_offer', 'enchant_card', 1, enchantment='swift', selection='random_eligible'),),
    'glitter': (_rule('card_offer', 'enchant_offers', 1, enchantment='glam'),),
    'dingy_rug': (_rule('card_reward_pool', 'add_colorless_cards', requires='matching_rarity_and_kind'),),
    'lasting_candy': (_rule('combat_card_reward', 'extra_power_option', 1, every=2, counter_scope='run'),),
    # run/rewards.py: reward creation; acquiring the result remains a choice.
    'amethyst_aubergine': (_rule('combat_gold_reward', 'gold', 15),),
    'white_beast_statue': (_rule('combat_reward', 'guarantee_potion_drop'),),

    # run/unknown_rooms.py, rest_site.py, shop.py and map_travel.py.
    'juzu_bracelet': (_rule('unknown_room_roll', 'exclude_room_kind', room_kind='combat'),),
    'regal_pillow': (_rule('rest', 'add_heal', 15, capped_at='missing_hp'),),
    'shovel': (_rule('rest_site', 'enable_relic_reward_option', 1, option='dig',
                     uses=1, scope='rest_site', optional_reward=True),),
    'miniature_tent': (_rule('rest_option_completed', 'allow_other_rest_options',
                             uses_per_distinct_option=1, scope='rest_site'),),
    'membership_card': (_rule('shop_price', 'amount_percent', 50,
                              includes='card_removal', rounding='floor_after_combined_discounts'),),
    'the_courier': (_rule('shop_price', 'amount_percent', 80,
                          includes='card_removal', rounding='floor_after_combined_discounts'),
                    _rule('shop_item_acquired', 'restock_slot', 1, requires='available_stock')),
    'lords_parasol': (_rule('shop_entered', 'obtain_original_stock_free',
                            requires='acquirable_item', respects_potion_capacity=True,
                            excludes='courier_restock'),
                      _rule('after_original_shop_stock', 'remove_card', 1,
                            selection='player', requires='eligible_removal_available',
                            gold_cost=0, optional=False)),
    'winged_boots': (_rule('map_travel', 'allow_unconnected_next_row', uses=3,
                           scope='run', charge_only_for_unconnected=True,
                           excludes='terminal_or_slice_end'),),
    'meat_cleaver': (_rule('rest_site', 'enable_cook_option', option='cook', uses=1, scope='rest_site'),
                     _rule('rest_cook', 'remove_card', 2, selection='player', requires='two_non_eternal_cards'),
                     _rule('after_rest_cook_removal', 'max_hp', 9)),

    # relics/pickup.py and ancient_pickups.py: counts are capped by eligibility.
    # Describe choices and their unavoidable costs separately from auto-grants.
    'astrolabe': (_pickup_selection('transform_card', 3, 3, requires='non_eternal',
                                    upgrade_result=True, pool='replacement_pool'),),
    'beautiful_bracelet': (_pickup_selection('enchant_card', 3, 3,
        enchantment='swift', amount=3, requires='can_enchant'),),
    'claws': (_pickup_selection('replace_card', 0, 6, card='maul', requires='non_eternal',
                                upgrade_level='preserve_up_to_new_cap', preserve_eligible_enchantment=True),),
    'electric_shrymp': (_pickup_selection('enchant_card', 1, 1,
        enchantment='imbued', amount=1, requires='can_enchant'),),
    'empty_cage': (_pickup_selection('remove_card', 2, 2, requires='non_eternal'),),
    'paels_growth': (_pickup_selection('enchant_card', 1, 1,
        enchantment='clone', amount=4, requires='can_enchant'),
        _rule('rest_clone', 'copy_card_to_deck', 1, per='clone_enchanted_card',
              uses=1, scope='rest_site', preserve_upgrade=True, preserve_enchantment=True)),
    'paels_tooth': (_pickup_selection('store_and_remove_card', 5, 5, requires='non_eternal_upgradable'),
                    _rule('combat_victory', 'return_stored_card', 1, selection='random',
                          requires='stored_cards_remaining', upgrade_result=True,
                          preserve_enchantment=True, preserve_permanent_damage_and_block=True)),
    'preserved_fog': (_pickup_selection('remove_card', 3, 3, requires='non_eternal'),
                      _rule('after_pickup_selection', 'add_card_to_deck', 1, card='folly',
                            also_when_no_eligible_cards=True)),
    'tri_boomerang': (_pickup_selection('enchant_card', 3, 3,
        enchantment='instinct', amount=1, requires='can_enchant'),),
    'yummy_cookie': (_pickup_selection('upgrade_card', 4, 4, requires='upgradable'),),
    'dollys_mirror': (_pickup_selection('copy_card_to_deck', 1, 1, requires='non_quest',
                                      preserve_upgrade=True, preserve_enchantment=True),),
    'gnarled_hammer': (_pickup_selection('enchant_card', 0, 3,
        enchantment='sharp', amount=3, requires='can_enchant'),),
    'kifuda': (_pickup_selection('enchant_card', 0, 3,
        enchantment='adroit', amount=3, requires='can_enchant'),),
    'punch_dagger': (_pickup_selection('enchant_card', 1, 1,
        enchantment='momentum', amount=5, requires='can_enchant'),),
    'royal_stamp': (_pickup_selection('enchant_card', 1, 1,
        enchantment='royally_approved', amount=1, requires='can_enchant'),),
    'new_leaf': (_pickup_selection('transform_card', 1, 1, requires='non_eternal', pool='replacement_pool'),),
    'pomander': (_pickup_selection('upgrade_card', 1, 1, requires='upgradable'),),
    'precise_scissors': (_pickup_selection('remove_card', 1, 1, requires='non_eternal'),),
    'precarious_shears': (_pickup_selection('remove_card', 2, 2, requires='non_eternal'),
                         _rule('after_pickup_selection', 'hp_loss', 16, also_when_no_eligible_cards=True)),
    'cauldron': (_rule('pickup', 'potion_reward', 5, optional=True),),
    'orrery': (_rule('pickup', 'card_reward', 5, offers_per_reward=3,
                     pool='character', optional=True),),
    'lost_coffer': (_rule('pickup', 'potion_reward', 1, optional=True),
                    _rule('pickup', 'card_reward', 1, offers_per_reward=3, pool='character', optional=True)),
    'lead_paperweight': (_rule('pickup', 'card_reward', 1, offers_per_reward=2,
                              pool='colorless', optional=True),),

    # relics/ancient_pickups.py and ancient_state.py: automatic grants and
    # subsequent effects. No sampled contents or stored private cards are read.
    'alchemical_coffer': (_rule('pickup', 'potion_slots', 4),
                          _rule('pickup', 'generate_potion', 4, destination='new_potion_slots',
                                selection='random', blocked_by='sozu')),
    'archaic_tooth': (_rule('pickup', 'replace_first_matching_card', 1, source='deck',
                            upgrade_level='preserve_up_to_new_cap', preserve_eligible_enchantment=True,
                            **{'replacement.bash': 'break', 'replacement.neutralize': 'suppress',
                               'replacement.unleash': 'protector', 'replacement.falling_star': 'meteor_shower',
                               'replacement.dualcast': 'quadcast'}),),
    'distinguished_cape': (_rule('pickup', 'max_hp', -9),
                           _rule('pickup_after_max_hp_loss', 'add_card_to_deck', 3,
                                 card='apparition', requires='alive')),
    'dusty_tome': (_rule('pickup', 'add_card_to_deck', 1, pool='character_ancient_cards',
                         selection='offered_card_or_random', upgrade_level=1),),
    'calling_bell': (_rule('pickup', 'add_card_to_deck', 1, card='curse_of_the_bell'),
                     _rule('pickup', 'relic_reward', 1, rarity='common', optional=True),
                     _rule('pickup', 'relic_reward', 1, rarity='uncommon', optional=True),
                     _rule('pickup', 'relic_reward', 1, rarity='rare', optional=True)),
    'toy_box': (_rule('pickup', 'relic_reward', 4, wax=True, optional=True),
                _rule('combat_victory', 'melt_relic', 1, every=3, counter_scope='run',
                      target='first_remaining_unmelted_wax_relic')),
    'glass_eye': (_rule('pickup', 'card_reward', 2, rarity='common', offers_per_reward=3, optional=True),
                  _rule('pickup', 'card_reward', 2, rarity='uncommon', offers_per_reward=3, optional=True),
                  _rule('pickup', 'card_reward', 1, rarity='rare', offers_per_reward=3, optional=True)),
    'nutritious_soup': (_rule('pickup', 'enchant_card', 1, enchantment='tezcataras_ember',
                              target='all_basic_strikes', requires='can_enchant'),),
    'paels_claw': (_rule('pickup', 'enchant_card', 1, enchantment='goopy',
                         target='all_defends', requires='can_enchant'),),
    'pandoras_box': (_rule('pickup', 'transform_card', target='all_basic_strikes_and_defends',
                           requires='non_eternal', pool='replacement_pool'),),
    'sand_castle': (_rule('pickup', 'upgrade_card', 6, selection='random_upgradable'),),
    'sea_glass': (_rule('pickup', 'choose_cards', selection_minimum=0, selection_maximum=15,
                        offers_per_rarity=5, rarities='common_uncommon_rare',
                        pool='offered_character', ignore_reward_pool_changes=True),),
    'sere_talon': (_rule('pickup', 'add_card_to_deck', 2, pool='modifier_curses',
                         selection='random_distinct'),
                   _rule('pickup', 'add_card_to_deck', 3, card='wish')),
    'touch_of_orobas': (_rule('pickup', 'replace_starter_relic', 1, selection='first_owned_starter',
                              replacement='upgraded_starter', fallback='circlet'),),
    'jewelry_box': (_rule('pickup', 'add_card_to_deck', 1, card='apotheosis'),),
    'paels_horn': (_rule('pickup', 'add_card_to_deck', 2, card='relax'),),
    'storybook': (_rule('pickup', 'add_card_to_deck', 1, card='brightest_flame'),),
    'tanxs_whistle': (_rule('pickup', 'add_card_to_deck', 1, card='whistle'),),

    # relics/neow.py and generation/foreign.py.
    'arcane_scroll': (_rule('pickup', 'add_card_to_deck', 1, pool='character',
                            rarity='rare', selection='random'),),
    'cursed_pearl': (_rule('pickup', 'add_card_to_deck', 1, card='greed'),
                     _rule('pickup', 'gold', 333)),
    'hefty_tablet': (_rule('pickup', 'card_reward', 1, rarity='rare', pool='character',
                           offers_per_reward=3, optional=True),
                     _rule('after_pickup_reward', 'add_card_to_deck', 1, card='injury', also_when_skipped=True)),
    'large_capsule': (_rule('pickup', 'generate_relic', 2, pool='common_uncommon_rare', selection='random'),
                      _rule('pickup', 'add_card_to_deck', 1, card='character_basic_strike'),
                      _rule('pickup', 'add_card_to_deck', 1, card='character_basic_defend')),
    'small_capsule': (_rule('pickup', 'relic_reward', 1, pool='common_uncommon_rare', optional=True),),
    'leafy_poultice': (_rule('pickup', 'max_hp', -12),
                       _rule('pickup_after_max_hp_loss', 'transform_card', 1, card_family='basic_strike',
                             selection='first_matching_in_deck', requires='alive', pool='run_reward_cards'),
                       _rule('pickup_after_max_hp_loss', 'transform_card', 1, card_family='basic_defend',
                             selection='first_matching_in_deck', requires='alive', pool='run_reward_cards')),
    'neows_talisman': (_rule('pickup', 'upgrade_card', 1, card_family='basic_strike',
                             selection='last_matching_in_deck', requires='upgradable'),
                       _rule('pickup', 'upgrade_card', 1, card_family='basic_defend',
                             selection='last_matching_in_deck', requires='upgradable')),
    'neows_torment': (_rule('pickup', 'add_card_to_deck', 1, card='neows_fury'),),
    'phial_holster': (_rule('pickup', 'potion_slots', 1),
                      _rule('pickup', 'generate_potion', 2, selection='random',
                            requires='empty_potion_slot', blocked_by='sozu')),
    'scroll_boxes': (_rule('pickup', 'choose_card_bundle', 1, offers=2, cards_per_bundle=3,
                            common_cards_per_bundle=2, uncommon_cards_per_bundle=1,
                            pool='character', optional=False, defect_exception='rare_three_claw_bundle'),),
    'neows_bones': (_rule('pickup', 'relic_reward', 2, pool='other_available_neow_relics', optional=False),
                    _rule('after_pickup_rewards', 'add_card_to_deck', 1, pool='modifier_curses',
                          selection='random', requires='alive')),
    'kaleidoscope': (_rule('pickup', 'card_reward', 2, offers_per_reward=3,
                           pool='three_distinct_other_characters_per_reward', optional=True),),

    # relics/ancient_map.py, core/combat.py and encounters/randomness.py.
    'golden_compass': (_rule('pickup_at_act_start', 'replace_act_map', topology='golden_path',
                             scope='owning_act', branching=False),),
    'fur_coat': (_rule('pickup', 'mark_combat_nodes', 7, selection='random_normal_or_elite',
                        count_clipped_to_available=True, mark_generation_scope='acquisition_act'),
                 _rule('enemy_created_in_marked_combat', 'set_hp', 1,
                       requires='current_node_matches_saved_marked_coordinates',
                       includes='initial_and_spawned_enemies', maximum_hp_unchanged=True)),
    # relics/reward_alternatives.py, rewards.py and run/lifecycle.py.
    'driftwood': (_rule('eligible_card_reward', 'allow_reroll', 1, uses=1, scope='reward',
                         excludes='kaleidoscope_empty_reroll_pool'),),
    'lava_rock': (_rule('boss_victory_reward', 'extra_relic_reward', 2, uses=1,
                        scope='run', excludes='final_boss'),),
    'wongos_mystery_ticket': (_rule('combat_victory_reward', 'extra_relic_reward', 3,
                                    at_count=5, counter_scope='run', uses=1, scope='run',
                                    includes_final_boss=True),),
    # relics/event_content.py. These drawbacks are part of the descriptions.
    'fragrant_mushroom': (_rule('pickup', 'hp_loss', 15),
                          _rule('pickup_after_hp_loss', 'upgrade_card', 2, selection='random_upgradable')),
    'fake_lees_waffle': (_rule('pickup', 'heal_max_hp_percent', 10, rounding='floor'),),

    # No intrinsic effect in this engine. They still count as owned relics for
    # other mechanics; this does not claim that ownership is universally inert.
    'circlet': (_rule('owned', 'no_intrinsic_effect'),),
    'fake_merchants_rug': (_rule('owned', 'no_intrinsic_effect'),),
    'wongo_customer_appreciation_badge': (_rule('owned', 'no_intrinsic_effect'),),
})


def fields(name):
    """Fresh flat values; the source definitions above remain recursively frozen."""
    return {f'effect.{i}.{key}': value for i, rule in enumerate(RELIC_RULES.get(name, ()))
            for key, value in rule}
