"""Pinned 0.107.1 ordinary solo Defect cards and generated Fuel."""

from game.headless.cards.builders import define
from game.headless.cards.effects import GainBlock, DrawCards, SelectHandCard
from game.headless.cards.operations import Attack, Power, ChoosePileCard
from game.headless.cards.defect_effects import Defect, AddCardToDiscard
from game.headless.cards.orb_effects import Channel

DEFINITIONS = (
    define('adaptive_strike', 'Adaptive Strike', 2, 'attack', 'rare',
           (Attack(), Defect("adaptive"),), damage=18, upgraded_damage=23, target=True, strike=True, pool='defect'),
    define('all_for_one', 'All For One', 2, 'attack', 'rare',
           (Attack(), Defect("all_for_one"),), damage=10, upgraded_damage=14, target=True, pool='defect'),
    define('ball_lightning', 'Ball Lightning', 1, 'attack', 'common',
           (Attack(), Channel("lightning"),), damage=7, upgraded_damage=10, target=True, pool='defect'),
    define('barrage', 'Barrage', 1, 'attack', 'common',
           (Attack(hit_expression="orbs"),), damage=5, upgraded_damage=7, target=True, pool='defect'),
    define('beam_cell', 'Beam Cell', 0, 'attack', 'common',
           (Attack(), Power("vulnerable", 1, 2, target=True),), damage=3, upgraded_damage=4, target=True, pool='defect'),
    define('boost_away', 'Boost Away', 0, 'skill', 'common',
           (GainBlock(), AddCardToDiscard("dazed"),), block=6, upgraded_block=9, target=False, pool='defect'),
    define('boot_sequence', 'Boot Sequence', 0, 'skill', 'uncommon',
           (GainBlock(),), block=10, upgraded_block=13, target=False, exhaust=True, base_innate=True, innate=True, pool='defect'),
    define('buffer', 'Buffer', 2, 'power', 'rare',
           (Power("buffer", 1, 2),), target=False, pool='defect'),
    define('bulk_up', 'Bulk Up', 2, 'power', 'uncommon',
           (Defect("remove_slots", 1), Power("strength", 2, 3), Power("dexterity", 2, 3),), target=False, pool='defect'),
    define('capacitor', 'Capacitor', 1, 'power', 'uncommon',
           (Defect("slots", 2, 3),), target=False, pool='defect'),
    define('chaos', 'Chaos', 1, 'skill', 'uncommon',
           (Channel("random", 1, 2),), target=False, pool='defect'),
    define('charge_battery', 'Charge Battery', 1, 'skill', 'common',
           (GainBlock(), Power("energy_next_turn"),), block=7, upgraded_block=10, target=False, pool='defect'),
    define('chill', 'Chill', 0, 'skill', 'uncommon',
           (Channel("frost", count="enemies"),), target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('claw', 'Claw', 0, 'attack', 'common',
           (Attack(), Defect("claw", 2, 3),), damage=3, upgraded_damage=4, target=True, pool='defect'),
    define('cold_snap', 'Cold Snap', 1, 'attack', 'common',
           (Attack(), Channel("frost"),), damage=6, upgraded_damage=9, target=True, pool='defect'),
    define('compact', 'Compact', 1, 'skill', 'uncommon',
           (GainBlock(), Defect("compact"),), block=6, upgraded_block=7, target=False, pool='defect'),
    define('compile_driver', 'Compile Driver', 1, 'attack', 'common',
           (Attack(), Defect("compile_driver"),), damage=7, upgraded_damage=10, target=True, pool='defect'),
    define('consuming_shadow', 'Consuming Shadow', 2, 'power', 'rare',
           (Channel("dark", 2, 3), Power("consuming_shadow"),), target=False, pool='defect'),
    define('coolant', 'Coolant', 1, 'power', 'rare',
           (Power("coolant", 2, 3),), target=False, pool='defect'),
    define('coolheaded', 'Coolheaded', 1, 'skill', 'common',
           (Channel("frost"), DrawCards(),), draw=1, upgraded_draw=2, target=False, pool='defect'),
    define('creative_ai', 'Creative Ai', 3, 'power', 'rare',
           (Power("creative_ai"),), upgraded_cost=2, target=False, pool='defect'),
    define('darkness', 'Darkness', 1, 'skill', 'uncommon',
           (Channel("dark"), Defect("darkness", 1, 2),), target=False, pool='defect'),
    define('defend_defect', 'Defend Defect', 1, 'skill', 'basic',
           (GainBlock(),), block=5, upgraded_block=8, target=False, defend=True, pool='defect'),
    define('defragment', 'Defragment', 1, 'power', 'rare',
           (Defect("focus", 1, 2),), target=False, pool='defect'),
    define('double_energy', 'Double Energy', 1, 'skill', 'uncommon',
           (Defect("double_energy"),), upgraded_cost=0, target=False, exhaust=True, pool='defect'),
    define('dualcast', 'Dualcast', 1, 'skill', 'basic',
           (Defect("evoke", 2),), upgraded_cost=0, target=False, pool='defect'),
    define('echo_form', 'Echo Form', 3, 'power', 'rare',
           (Power("echo_form"),), target=False, ethereal=True, upgraded_ethereal=False, pool='defect'),
    define('feral', 'Feral', 2, 'power', 'uncommon',
           (Power("feral"),), upgraded_cost=1, target=False, pool='defect'),
    define('fight_through', 'Fight Through', 1, 'skill', 'uncommon',
           (GainBlock(), AddCardToDiscard("wound", 2),), block=13, upgraded_block=17, target=False, pool='defect'),
    define('flak_cannon', 'Flak Cannon', 2, 'attack', 'rare',
           (Defect("flak_cannon"),), damage=8, upgraded_damage=11, target=False, pool='defect'),
    define('focused_strike', 'Focused Strike', 1, 'attack', 'common',
           (Attack(), Power("focused_strike", 1, 2),), damage=9, upgraded_damage=11, target=True, strike=True, pool='defect'),
    define('ftl', 'Ftl', 0, 'attack', 'uncommon',
           (Attack(), Defect("ftl", 3, 4),), damage=5, upgraded_damage=6, draw=1, target=True, pool='defect'),
    define('fusion', 'Fusion', 1, 'skill', 'uncommon',
           (Channel("plasma"),), target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('genetic_algorithm', 'Genetic Algorithm', 1, 'skill', 'rare',
           (GainBlock(), Defect("genetic", 3, 4),), block=1, target=False, exhaust=True, pool='defect'),
    define('glacier', 'Glacier', 2, 'skill', 'uncommon',
           (GainBlock(), Channel("frost", 2),), block=6, upgraded_block=9, target=False, pool='defect'),
    define('glasswork', 'Glasswork', 1, 'skill', 'uncommon',
           (GainBlock(), Channel("glass"),), block=5, upgraded_block=8, target=False, pool='defect'),
    define('go_for_the_eyes', 'Go For The Eyes', 0, 'attack', 'common',
           (Attack(), Defect("eyes", 1, 2),), damage=3, upgraded_damage=4, target=True, pool='defect'),
    define('gunk_up', 'Gunk Up', 1, 'attack', 'common',
           (Attack(hits=3), AddCardToDiscard("slimed"),), damage=4, upgraded_damage=5, target=True, pool='defect'),
    define('hailstorm', 'Hailstorm', 1, 'power', 'uncommon',
           (Power("hailstorm", 6, 8),), target=False, pool='defect'),
    define('helix_drill', 'Helix Drill', 0, 'attack', 'rare',
           (Attack(hit_expression="spent_energy"),), damage=3, upgraded_damage=5, target=True, pool='defect'),
    define('hologram', 'Hologram', 1, 'skill', 'common',
           (GainBlock(), ChoosePileCard("discard_pile", destination="hand"),), block=3, upgraded_block=5, target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('hotfix', 'Hotfix', 0, 'skill', 'common',
           (Power("hotfix", 2),), target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('hyperbeam', 'Hyperbeam', 2, 'attack', 'rare',
           (Attack(all_enemies=True), Defect("focus", -3),), damage=28, upgraded_damage=36, target=False, pool='defect'),
    define('ice_lance', 'Ice Lance', 3, 'attack', 'rare',
           (Attack(), Channel("frost", 3),), damage=19, upgraded_damage=24, target=True, pool='defect'),
    define('iteration', 'Iteration', 1, 'power', 'uncommon',
           (Power("defect_iteration", 2, 3),), target=False, pool='defect'),
    define('leap', 'Leap', 1, 'skill', 'common',
           (GainBlock(),), block=9, upgraded_block=12, target=False, pool='defect'),
    define('lightning_rod', 'Lightning Rod', 1, 'skill', 'common',
           (GainBlock(), Power("lightning_rod", 2),), block=4, upgraded_block=7, target=False, pool='defect'),
    define('loop', 'Loop', 1, 'power', 'uncommon',
           (Power("loop", 1, 2),), target=False, pool='defect'),
    define('machine_learning', 'Machine Learning', 1, 'power', 'rare',
           (Power("machine_learning"),), draw=1, target=False, innate=True, pool='defect'),
    define('meteor_strike', 'Meteor Strike', 5, 'attack', 'rare',
           (Attack(), Channel("plasma", 3),), damage=24, upgraded_damage=30, target=True, strike=True, pool='defect'),
    define('modded', 'Modded', 0, 'skill', 'rare',
           (Defect("slots", 1), DrawCards(), Defect("cost_increase", 1),), draw=1, upgraded_draw=2, target=False, pool='defect'),
    define('momentum_strike', 'Momentum Strike', 1, 'attack', 'common',
           (Attack(), Defect("zero_combat"),), damage=10, upgraded_damage=13, target=True, strike=True, pool='defect'),
    define('multi_cast', 'Multi Cast', 0, 'skill', 'rare',
           (Defect("multi_cast"),), target=False, x=True, pool='defect'),
    define('null', 'Null', 2, 'attack', 'uncommon',
           (Attack(), Power("weak", 2, 3, target=True), Channel("dark"),), damage=10, upgraded_damage=13, target=True, pool='defect'),
    define('overclock', 'Overclock', 0, 'skill', 'uncommon',
           (DrawCards(), AddCardToDiscard("burn"),), draw=2, upgraded_draw=3, target=False, pool='defect'),
    define('rainbow', 'Rainbow', 2, 'skill', 'rare',
           (Channel("lightning"), Channel("frost"), Channel("dark"),), target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('reboot', 'Reboot', 0, 'skill', 'rare',
           (Defect("reboot"), DrawCards(),), draw=4, upgraded_draw=6, target=False, exhaust=True, pool='defect'),
    define('refract', 'Refract', 3, 'attack', 'uncommon',
           (Attack(hits=2), Channel("glass", 2),), damage=9, upgraded_damage=12, target=True, pool='defect'),
    define('rocket_punch', 'Rocket Punch', 2, 'attack', 'uncommon',
           (Attack(), DrawCards(),), damage=13, upgraded_damage=14, draw=1, upgraded_draw=2, target=True, pool='defect'),
    define('scavenge', 'Scavenge', 1, 'skill', 'uncommon',
           (SelectHandCard("exhaust"), Power("energy_next_turn", 2, 3),), target=False, pool='defect'),
    define('scrape', 'Scrape', 1, 'attack', 'uncommon',
           (Attack(), Defect("scrape"),), damage=7, upgraded_damage=10, draw=4, upgraded_draw=5, target=True, pool='defect'),
    define('shadow_shield', 'Shadow Shield', 2, 'skill', 'uncommon',
           (GainBlock(), Channel("dark"),), block=11, upgraded_block=15, target=False, pool='defect'),
    define('shatter', 'Shatter', 1, 'attack', 'rare',
           (Attack(all_enemies=True), Defect("shatter"),), damage=7, upgraded_damage=11, target=False, pool='defect'),
    define('signal_boost', 'Signal Boost', 1, 'skill', 'rare',
           (Power("signal_boost"),), upgraded_cost=0, target=False, exhaust=True, pool='defect'),
    define('skim', 'Skim', 1, 'skill', 'uncommon',
           (DrawCards(),), draw=3, upgraded_draw=4, target=False, pool='defect'),
    define('smokestack', 'Smokestack', 1, 'power', 'uncommon',
           (Power("smokestack", 5, 7),), target=False, pool='defect'),
    define('spinner', 'Spinner', 1, 'power', 'rare',
           (Channel("glass", 0, 1), Power("spinner"),), target=False, pool='defect'),
    define('storm', 'Storm', 1, 'power', 'uncommon',
           (Power("storm", 1, 2),), target=False, pool='defect'),
    define('strike_defect', 'Strike Defect', 1, 'attack', 'basic',
           (Attack(),), damage=6, upgraded_damage=9, target=True, strike=True, pool='defect'),
    define('subroutine', 'Subroutine', 1, 'power', 'uncommon',
           (Power("subroutine"),), upgraded_cost=0, target=False, pool='defect'),
    define('sunder', 'Sunder', 3, 'attack', 'uncommon',
           (Defect("sunder", 3),), damage=24, upgraded_damage=32, target=True, pool='defect'),
    define('supercritical', 'Supercritical', 0, 'skill', 'rare',
           (Defect("energy", 4, 6),), target=False, exhaust=True, pool='defect'),
    define('sweeping_beam', 'Sweeping Beam', 1, 'attack', 'common',
           (Attack(all_enemies=True), DrawCards(),), damage=6, upgraded_damage=9, draw=1, target=False, pool='defect'),
    define('synchronize', 'Synchronize', 1, 'skill', 'uncommon',
           (Defect("synchronize"),), target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('synthesis', 'Synthesis', 2, 'attack', 'uncommon',
           (Attack(), Power("free_power"),), damage=14, upgraded_damage=20, target=True, pool='defect'),
    define('tempest', 'Tempest', 0, 'skill', 'uncommon',
           (Channel("lightning", count="x"),), target=False, x=True, pool='defect'),
    define('tesla_coil', 'Tesla Coil', 0, 'attack', 'uncommon',
           (Attack(), Defect("tesla", 1, 2),), damage=3, upgraded_damage=4, target=True, pool='defect'),
    define('thunder', 'Thunder', 1, 'power', 'uncommon',
           (Power("thunder", 6, 8),), target=False, pool='defect'),
    define('trash_to_treasure', 'Trash To Treasure', 1, 'power', 'rare',
           (Power("trash_to_treasure"),), target=False, innate=True, pool='defect'),
    define('turbo', 'Turbo', 0, 'skill', 'common',
           (Defect("energy", 2, 3), AddCardToDiscard("void"),), target=False, pool='defect'),
    define('uproar', 'Uproar', 2, 'attack', 'common',
           (Attack(hits=2), Defect("uproar"),), damage=6, upgraded_damage=8, target=True, pool='defect'),
    define('voltaic', 'Voltaic', 3, 'skill', 'rare',
           (Channel("lightning", count="history"),), target=False, exhaust=True, upgraded_exhaust=False, pool='defect'),
    define('white_noise', 'White Noise', 1, 'skill', 'uncommon',
           (Defect("white_noise"),), upgraded_cost=0, target=False, exhaust=True, pool='defect'),
    define('zap', 'Zap', 1, 'skill', 'basic',
           (Channel("lightning"),), upgraded_cost=0, target=False, pool='defect'),
    define('fuel', 'Fuel', 0, 'skill', 'token',
           (Defect("energy", 1), DrawCards(),), draw=1, upgraded_draw=2, target=False, exhaust=True, pool='token'),
)

ORDINARY_IDS = tuple(d.definition_id for d in DEFINITIONS if d.rarity in ("common", "uncommon", "rare"))
