"""Remaining single-player Ironclad cards for the pinned 0.107.1 build."""

from dataclasses import replace
from game.headless.cards.base import CardDefinition, CardSpec
from game.headless.cards.effects import GainBlock, DrawCards, SelectHandCard, ApplyDebuffs
from game.headless.cards.operations import Attack, Power, CardOperation as Op, ChoosePileCard


def define(
    identity,
    name,
    cost,
    kind,
    rarity,
    effects,
    *,
    damage=0,
    upgraded_damage=None,
    block=0,
    upgraded_block=None,
    draw=0,
    upgraded_draw=None,
    upgraded_cost=None,
    target=None,
    exhaust=False,
    upgraded_exhaust=None,
    innate=False,
    strike=False,
    x=False,
    generate=True,
):
    base = CardSpec(
        name,
        cost,
        kind,
        base_damage=damage,
        block_gain=block,
        draw_count=draw,
        uses_target=kind == "attack" if target is None else target,
        exhausts=exhaust,
        x_cost=x,
    )
    upgrade = replace(
        base,
        name=name + "+",
        cost=cost if upgraded_cost is None else upgraded_cost,
        base_damage=damage if upgraded_damage is None else upgraded_damage,
        block_gain=block if upgraded_block is None else upgraded_block,
        draw_count=draw if upgraded_draw is None else upgraded_draw,
        exhausts=exhaust if upgraded_exhaust is None else upgraded_exhaust,
        innate=innate,
    )
    return CardDefinition(
        identity,
        (base, upgrade),
        effects,
        rarity=rarity,
        pool="ironclad",
        strike=strike,
        generate_in_combat=generate,
    )


# Values and composition are explicit; no display-name dispatch or runtime registration.
DEFINITIONS = (
    define("aggression", "Aggression", 1, "power", "rare", (Power("aggression"),), innate=True),
    define("anger", "Anger", 0, "attack", "common", (Attack(), Op("clone")), damage=6, upgraded_damage=8),
    define(
        "ashen_strike",
        "Ashen Strike",
        1,
        "attack",
        "uncommon",
        (Attack(expression="exhaust", factor=3, upgraded_factor=4),),
        damage=6,
        strike=True,
    ),
    define("barricade", "Barricade", 3, "power", "rare", (Power("barricade"),), upgraded_cost=2),
    define(
        "battle_trance",
        "Battle Trance",
        0,
        "skill",
        "uncommon",
        (DrawCards(), Power("no_draw")),
        draw=3,
        upgraded_draw=4,
    ),
    define(
        "blood_wall",
        "Blood Wall",
        2,
        "skill",
        "common",
        (Op("hp_loss", 2), GainBlock()),
        block=16,
        upgraded_block=20,
    ),
    define("bloodletting", "Bloodletting", 0, "skill", "common", (Op("hp_loss", 3), Op("energy", 2, 3))),
    define("bludgeon", "Bludgeon", 3, "attack", "uncommon", (Attack(),), damage=32, upgraded_damage=42),
    define(
        "brand",
        "Brand",
        0,
        "skill",
        "rare",
        (Op("hp_loss", 1), SelectHandCard("exhaust"), Power("strength", 1, 2)),
    ),
    define(
        "break",
        "Break",
        1,
        "attack",
        "ancient",
        (Attack(), Power("vulnerable", 5, 7, target=True)),
        damage=20,
        upgraded_damage=30,
    ),
    define(
        "breakthrough",
        "Breakthrough",
        1,
        "attack",
        "common",
        (Op("hp_loss", 1), Attack(all_enemies=True)),
        damage=9,
        upgraded_damage=13,
        target=False,
    ),
    define(
        "bully",
        "Bully",
        0,
        "attack",
        "uncommon",
        (Attack(expression="vulnerable", factor=2, upgraded_factor=3),),
        damage=4,
    ),
    define(
        "burning_pact",
        "Burning Pact",
        1,
        "skill",
        "uncommon",
        (SelectHandCard("exhaust"), DrawCards()),
        draw=2,
        upgraded_draw=3,
    ),
    define("cascade", "Cascade", -1, "skill", "rare", (Op("cascade"),), x=True),
    define(
        "cinder",
        "Cinder",
        2,
        "attack",
        "common",
        (Attack(), Op("random_exhaust")),
        damage=18,
        upgraded_damage=24,
    ),
    define(
        "colossus",
        "Colossus",
        1,
        "skill",
        "uncommon",
        (GainBlock(), Power("colossus")),
        block=5,
        upgraded_block=8,
    ),
    define(
        "conflagration",
        "Conflagration",
        1,
        "attack",
        "rare",
        (Attack(hits=4, upgraded_hits=5, all_enemies=True),),
        damage=2,
        target=False,
    ),
    define("corruption", "Corruption", 3, "power", "ancient", (Power("corruption"),), upgraded_cost=2),
    define("crimson_mantle", "Crimson Mantle", 1, "power", "rare", (Power("crimson_mantle", 8, 10),)),
    define("cruelty", "Cruelty", 1, "power", "rare", (Power("cruelty", 25, 50),)),
    define("dark_embrace", "Dark Embrace", 2, "power", "rare", (Power("dark_embrace"),), upgraded_cost=1),
    define("demon_form", "Demon Form", 3, "power", "rare", (Power("demon_form", 2, 3),)),
    define(
        "dismantle",
        "Dismantle",
        1,
        "attack",
        "uncommon",
        (Attack(hit_expression="vulnerable"),),
        damage=8,
        upgraded_damage=10,
    ),
    define(
        "dominate",
        "Dominate",
        1,
        "skill",
        "uncommon",
        (Power("vulnerable", 1, 2, target=True), Op("dominate")),
        target=True,
        exhaust=True,
    ),
    define("drum_of_battle", "Drum of Battle", 1, "skill", "uncommon", (DrawCards(),), draw=2),
    define("evil_eye", "Evil Eye", 1, "skill", "uncommon", (Op("evil_eye"),), block=8, upgraded_block=11),
    define(
        "expect_a_fight",
        "Expect a Fight",
        2,
        "skill",
        "uncommon",
        (Op("energy_from_attacks"),),
        upgraded_cost=1,
    ),
    define(
        "feed",
        "Feed",
        1,
        "attack",
        "rare",
        (Attack(fatal_max_hp=3, upgraded_max_hp=4),),
        damage=10,
        upgraded_damage=12,
        exhaust=True,
        generate=False,
    ),
    define("feel_no_pain", "Feel No Pain", 1, "power", "uncommon", (Power("feel_no_pain", 3, 4),)),
    define(
        "fight_me",
        "Fight Me",
        2,
        "attack",
        "uncommon",
        (Attack(hits=2), Power("strength", 3, 4), Power("strength", 1, target=True)),
        damage=5,
        upgraded_damage=6,
    ),
    define(
        "flame_barrier",
        "Flame Barrier",
        2,
        "skill",
        "uncommon",
        (GainBlock(), Power("flame_barrier", 4, 6)),
        block=12,
        upgraded_block=16,
    ),
    define(
        "forgotten_ritual",
        "Forgotten Ritual",
        1,
        "skill",
        "uncommon",
        (Op("energy_if_exhausted", 3, 4),),
        exhaust=True,
    ),
    define("havoc", "Havoc", 1, "skill", "common", (Op("havoc"),), upgraded_cost=0),
    define(
        "headbutt",
        "Headbutt",
        1,
        "attack",
        "common",
        (Attack(), ChoosePileCard()),
        damage=9,
        upgraded_damage=12,
    ),
    define("hellraiser", "Hellraiser", 2, "power", "rare", (Power("hellraiser"),), upgraded_cost=1),
    define(
        "hemokinesis",
        "Hemokinesis",
        1,
        "attack",
        "uncommon",
        (Op("hp_loss", 2), Attack()),
        damage=14,
        upgraded_damage=19,
    ),
    define(
        "howl_from_beyond",
        "Howl from Beyond",
        3,
        "attack",
        "uncommon",
        (Attack(all_enemies=True),),
        damage=16,
        upgraded_damage=21,
        target=False,
    ),
    define(
        "infernal_blade",
        "Infernal Blade",
        1,
        "skill",
        "uncommon",
        (Op("infernal_blade"),),
        exhaust=True,
        upgraded_cost=0,
    ),
    define("inferno", "Inferno", 1, "power", "uncommon", (Power("inferno", 6, 9),)),
    define("inflame", "Inflame", 1, "power", "uncommon", (Power("strength", 2, 3),)),
    define("juggernaut", "Juggernaut", 2, "power", "rare", (Power("juggernaut", 6, 8),)),
    define("juggling", "Juggling", 1, "power", "uncommon", (Power("juggling"),), innate=True),
    define(
        "mangle",
        "Mangle",
        3,
        "attack",
        "rare",
        (Attack(), Power("mangle", 10, 15, target=True)),
        damage=15,
        upgraded_damage=20,
    ),
    define(
        "molten_fist",
        "Molten Fist",
        1,
        "attack",
        "common",
        (Attack(), Op("double_vulnerable")),
        damage=10,
        upgraded_damage=14,
        exhaust=True,
    ),
    define("not_yet", "Not Yet", 2, "skill", "rare", (Op("heal", 10, 13),), exhaust=True, generate=False),
    define("one_two_punch", "One-Two Punch", 1, "skill", "rare", (Power("one_two_punch", 1, 2),)),
    define(
        "pacts_end",
        "Pact's End",
        0,
        "attack",
        "rare",
        (Attack(hit_expression="pacts_end", all_enemies=True),),
        damage=17,
        upgraded_damage=23,
        target=False,
    ),
    define(
        "perfected_strike",
        "Perfected Strike",
        2,
        "attack",
        "common",
        (Attack(expression="strikes", factor=2, upgraded_factor=3),),
        damage=6,
        strike=True,
    ),
    define(
        "pillage", "Pillage", 1, "attack", "uncommon", (Attack(), Op("pillage")), damage=6, upgraded_damage=9
    ),
    define("primal_force", "Primal Force", 0, "skill", "rare", (Op("primal_force"),)),
    define("pyre", "Pyre", 2, "power", "rare", (Power("pyre", 1, 2),)),
    define("rage", "Rage", 0, "skill", "uncommon", (Power("rage", 3, 5),)),
    define("rampage", "Rampage", 1, "attack", "uncommon", (Attack(), Op("rampage", 5, 9)), damage=9),
    define("rupture", "Rupture", 1, "power", "uncommon", (Power("rupture", 1, 2),)),
    define(
        "second_wind", "Second Wind", 1, "skill", "uncommon", (Op("second_wind"),), block=5, upgraded_block=7
    ),
    define(
        "setup_strike",
        "Setup Strike",
        1,
        "attack",
        "common",
        (Attack(), Power("setup_strike", 2, 3)),
        damage=7,
        upgraded_damage=9,
        strike=True,
    ),
    define(
        "spite",
        "Spite",
        0,
        "attack",
        "uncommon",
        (Attack(hits=2, upgraded_hits=3, hit_expression="spite"),),
        damage=5,
    ),
    define("stampede", "Stampede", 2, "power", "uncommon", (Power("stampede"),), upgraded_cost=1),
    define("stoke", "Stoke", 1, "skill", "rare", (Op("stoke"),)),
    define(
        "stomp",
        "Stomp",
        3,
        "attack",
        "uncommon",
        (Attack(all_enemies=True),),
        damage=12,
        upgraded_damage=15,
        target=False,
    ),
    define("stone_armor", "Stone Armor", 1, "power", "uncommon", (Power("plating", 4, 6),)),
    define(
        "taunt",
        "Taunt",
        1,
        "skill",
        "uncommon",
        (GainBlock(), Power("vulnerable", 1, 2, target=True)),
        block=7,
        upgraded_block=8,
        target=True,
    ),
    define(
        "tear_asunder",
        "Tear Asunder",
        2,
        "attack",
        "rare",
        (Attack(hit_expression="hp_loss"),),
        damage=5,
        upgraded_damage=7,
    ),
    define(
        "thrash", "Thrash", 1, "attack", "rare", (Attack(hits=2), Op("thrash")), damage=4, upgraded_damage=6
    ),
    define(
        "thunderclap",
        "Thunderclap",
        1,
        "attack",
        "common",
        (Attack(all_enemies=True), Op("area_vulnerable", 1)),
        damage=4,
        upgraded_damage=7,
        target=False,
    ),
    define(
        "tremble",
        "Tremble",
        1,
        "skill",
        "common",
        (Power("vulnerable", 3, 4, target=True),),
        target=True,
        exhaust=True,
    ),
    define(
        "twin_strike",
        "Twin Strike",
        1,
        "attack",
        "common",
        (Attack(hits=2),),
        damage=5,
        upgraded_damage=7,
        strike=True,
    ),
    define("unmovable", "Unmovable", 2, "power", "rare", (Power("unmovable"),), upgraded_cost=1),
    define(
        "unrelenting",
        "Unrelenting",
        2,
        "attack",
        "uncommon",
        (Attack(), Power("free_attack")),
        damage=14,
        upgraded_damage=20,
    ),
    define("vicious", "Vicious", 1, "power", "uncommon", (Power("vicious", 1, 2),)),
    define(
        "whirlwind",
        "Whirlwind",
        0,
        "attack",
        "uncommon",
        (Attack(hit_expression="x", all_enemies=True),),
        damage=5,
        upgraded_damage=8,
        target=False,
        x=True,
    ),
)
GIANT_ROCK = replace(
    define("giant_rock", "Giant Rock", 1, "attack", "token", (Attack(),), damage=16, upgraded_damage=20),
    pool="colorless",
)
