"""Pinned 0.107.1 solo Necrobinder rules, including acquired-card dependencies."""

from game.headless.cards.builders import define
from game.headless.cards.effects import GainBlock, DrawCards
from game.headless.cards.operations import Attack, Power
from game.headless.cards.silent_effects import Silent
from game.headless.cards.necrobinder_effects import Necro
from game.headless.cards.osty_effects import OstyAttack

DEFINITIONS = (
    define('afterlife', 'Afterlife', 1, 'skill', 'common',
           (Necro("summon", 6, 9),), target=False, exhaust=True, pool='necrobinder'),
    define('banshees_cry', 'Banshees Cry', 9, 'attack', 'rare',
           (Attack(all_enemies=True),), damage=33, upgraded_cost=7, target=False, pool='necrobinder'),
    define('blight_strike', 'Blight Strike', 1, 'attack', 'common',
           (Necro("blight"),), damage=8, upgraded_damage=10, target=True, strike=True, pool='necrobinder'),
    define('bodyguard', 'Bodyguard', 1, 'skill', 'basic',
           (Necro("summon", 5, 7),), target=False, pool='necrobinder'),
    define('bone_shards', 'Bone Shards', 1, 'attack', 'uncommon',
           (OstyAttack(after="bone_shards"),), damage=9, upgraded_damage=12, block=9, upgraded_block=12, target=False, pool='necrobinder'),
    define('borrowed_time', 'Borrowed Time', 1, 'skill', 'uncommon',
           (Silent("energy", 4, 6), Power("borrowed_time"),), target=False, pool='necrobinder'),
    define('bury', 'Bury', 4, 'attack', 'uncommon',
           (Attack(),), damage=52, upgraded_damage=63, target=True, pool='necrobinder'),
    define('calcify', 'Calcify', 1, 'power', 'uncommon',
           (Power("calcify", 4, 6),), target=False, pool='necrobinder'),
    define('call_of_the_void', 'Call Of The Void', 1, 'power', 'rare',
           (Power("call_of_the_void"),), target=False, innate=True, pool='necrobinder'),
    define('capture_spirit', 'Capture Spirit', 1, 'skill', 'uncommon',
           (Necro("capture_spirit", 3, 4),), damage=3, upgraded_damage=4, target=True, pool='necrobinder'),
    define('cleanse', 'Cleanse', 1, 'skill', 'uncommon',
           (Necro("summon", 3, 5), Necro("cleanse"),), target=False, pool='necrobinder'),
    define('countdown', 'Countdown', 1, 'power', 'uncommon',
           (Power("countdown", 6, 9),), target=False, pool='necrobinder'),
    define('danse_macabre', 'Danse Macabre', 1, 'power', 'uncommon',
           (Power("danse_macabre", 4, 6),), target=False, pool='necrobinder'),
    define('death_march', 'Death March', 1, 'attack', 'uncommon',
           (Attack(expression="turn_draws", factor=4, upgraded_factor=6),), damage=8, upgraded_damage=9, target=True, pool='necrobinder'),
    define('deathbringer', 'Deathbringer', 2, 'skill', 'uncommon',
           (Necro("area_doom", 21, 26), Necro("area_weak", 1),), target=False, pool='necrobinder'),
    define('deaths_door', 'Deaths Door', 1, 'skill', 'uncommon',
           (Necro("deaths_door"),), block=6, upgraded_block=7, target=False, pool='necrobinder'),
    define('debilitate', 'Debilitate', 1, 'attack', 'uncommon',
           (Attack(), Power("debilitate", 2, 3, target=True),), damage=10, upgraded_damage=12, target=True, pool='necrobinder'),
    define('defend_necrobinder', 'Defend Necrobinder', 1, 'skill', 'basic',
           (GainBlock(),), block=5, upgraded_block=8, target=False, defend=True, pool='necrobinder'),
    define('defile', 'Defile', 1, 'attack', 'common',
           (Attack(),), damage=13, upgraded_damage=17, target=True, ethereal=True, pool='necrobinder'),
    define('defy', 'Defy', 1, 'skill', 'common',
           (GainBlock(), Power("weak", target=True),), block=6, upgraded_block=9, target=True, ethereal=True, pool='necrobinder'),
    define('delay', 'Delay', 2, 'skill', 'uncommon',
           (GainBlock(), Power("energy_next_turn", 1, 2),), block=11, upgraded_block=13, target=False, pool='necrobinder'),
    define('demesne', 'Demesne', 3, 'power', 'rare',
           (Power("demesne"),), upgraded_cost=2, target=False, ethereal=True, pool='necrobinder'),
    define('devour_life', 'Devour Life', 1, 'power', 'rare',
           (Power("devour_life", 1, 2),), target=False, pool='necrobinder'),
    define('dirge', 'Dirge', 0, 'skill', 'uncommon',
           (Necro("dirge", 3, 4),), target=False, exhaust=True, x=True, pool='necrobinder'),
    define('drain_power', 'Drain Power', 1, 'attack', 'common',
           (Attack(), Necro("drain_power", 2, 3),), damage=10, upgraded_damage=12, target=True, pool='necrobinder'),
    define('dredge', 'Dredge', 1, 'skill', 'uncommon',
           (Necro("dredge", 3),), target=False, exhaust=True, upgraded_retain=True, pool='necrobinder'),
    define('eidolon', 'Eidolon', 2, 'skill', 'rare',
           (Necro("eidolon"),), upgraded_cost=1, target=False, pool='necrobinder'),
    define('end_of_days', 'End Of Days', 3, 'skill', 'rare',
           (Necro("area_doom", 29, 37), Necro("doom_kill"),), target=False, pool='necrobinder'),
    define('enfeebling_touch', 'Enfeebling Touch', 1, 'skill', 'uncommon',
           (Power("enfeebling_touch", 8, 11, target=True),), target=True, ethereal=True, pool='necrobinder'),
    define('eradicate', 'Eradicate', 0, 'attack', 'rare',
           (Attack(hit_expression="x"),), damage=11, upgraded_damage=14, target=True, retain=True, x=True, pool='necrobinder'),
    define('fear', 'Fear', 1, 'attack', 'common',
           (Attack(), Power("vulnerable", 1, 2, target=True),), damage=7, upgraded_damage=8, target=True, ethereal=True, pool='necrobinder'),
    define('fetch', 'Fetch', 0, 'attack', 'uncommon',
           (OstyAttack(after="fetch"),), damage=3, upgraded_damage=6, target=True, pool='necrobinder'),
    define('flatten', 'Flatten', 2, 'attack', 'common',
           (OstyAttack(),), damage=12, upgraded_damage=16, target=True, pool='necrobinder'),
    define('friendship', 'Friendship', 1, 'power', 'uncommon',
           (Necro("strength_loss", 2, 1), Power("friendship"),), target=False, pool='necrobinder'),
    define('grave_warden', 'Grave Warden', 1, 'skill', 'common',
           (GainBlock(), Necro("souls", 1),), block=8, upgraded_block=11, target=False, pool='necrobinder'),
    define('graveblast', 'Graveblast', 1, 'attack', 'common',
           (Attack(), Necro("graveblast"),), damage=4, upgraded_damage=6, target=True, exhaust=True, upgraded_exhaust=False, pool='necrobinder'),
    define('hang', 'Hang', 1, 'attack', 'rare',
           (Attack(), Necro("hang"),), damage=10, upgraded_damage=13, target=True, pool='necrobinder'),
    define('haunt', 'Haunt', 1, 'power', 'uncommon',
           (Power("haunt", 6, 8),), target=False, pool='necrobinder'),
    define('high_five', 'High Five', 2, 'attack', 'uncommon',
           (OstyAttack(all_enemies=True, after="high_five"),), damage=11, upgraded_damage=13, target=False, pool='necrobinder'),
    define('invoke', 'Invoke', 1, 'skill', 'common',
           (Power("summon_next_turn", 2, 3), Power("energy_next_turn", 2, 3),), target=False, pool='necrobinder'),
    define('lethality', 'Lethality', 1, 'power', 'uncommon',
           (Power("lethality", 50, 75),), target=False, ethereal=True, pool='necrobinder'),
    define('melancholy', 'Melancholy', 3, 'skill', 'uncommon',
           (GainBlock(),), block=13, upgraded_block=17, target=False, pool='necrobinder'),
    define('misery', 'Misery', 0, 'attack', 'rare',
           (Necro("misery"),), damage=7, upgraded_damage=9, target=True, upgraded_retain=True, pool='necrobinder'),
    define('necro_mastery', 'Necro Mastery', 2, 'power', 'rare',
           (Necro("summon", 5, 8), Power("necro_mastery"),), target=False, pool='necrobinder'),
    define('negative_pulse', 'Negative Pulse', 1, 'skill', 'common',
           (GainBlock(), Necro("area_doom", 7, 11),), block=5, upgraded_block=6, target=False, pool='necrobinder'),
    define('neurosurge', 'Neurosurge', 0, 'power', 'rare',
           (Silent("energy", 3, 4), DrawCards(), Power("neurosurge", 3),), draw=2, target=False, pool='necrobinder'),
    define('no_escape', 'No Escape', 1, 'skill', 'uncommon',
           (Necro("no_escape", 10, 15),), target=True, pool='necrobinder'),
    define('oblivion', 'Oblivion', 0, 'skill', 'rare',
           (Power("oblivion", 3, 4, target=True),), target=True, pool='necrobinder'),
    define('pagestorm', 'Pagestorm', 1, 'power', 'uncommon',
           (Power("pagestorm"),), upgraded_cost=0, target=False, pool='necrobinder'),
    define('parse', 'Parse', 1, 'skill', 'uncommon',
           (DrawCards(),), draw=3, upgraded_draw=4, target=False, ethereal=True, pool='necrobinder'),
    define('poke', 'Poke', 0, 'attack', 'common',
           (OstyAttack(),), damage=6, upgraded_damage=9, target=True, pool='necrobinder'),
    define('pull_aggro', 'Pull Aggro', 2, 'skill', 'common',
           (Necro("summon", 4, 5), GainBlock(),), block=7, upgraded_block=9, target=False, pool='necrobinder'),
    define('pull_from_below', 'Pull From Below', 1, 'attack', 'uncommon',
           (Attack(hit_expression="ethereal_plays"),), damage=5, upgraded_damage=7, target=True, pool='necrobinder'),
    define('putrefy', 'Putrefy', 1, 'skill', 'uncommon',
           (Power("weak", 2, 3, target=True), Power("vulnerable", 2, 3, target=True),), target=True, exhaust=True, pool='necrobinder'),
    define('rattle', 'Rattle', 1, 'attack', 'uncommon',
           (OstyAttack(hits="rattle"),), damage=7, upgraded_damage=9, target=True, pool='necrobinder'),
    define('reanimate', 'Reanimate', 3, 'skill', 'rare',
           (Necro("summon", 20, 25),), target=False, exhaust=True, pool='necrobinder'),
    define('reap', 'Reap', 3, 'attack', 'common',
           (Attack(),), damage=27, upgraded_damage=33, target=True, retain=True, pool='necrobinder'),
    define('reaper_form', 'Reaper Form', 3, 'power', 'rare',
           (Power("reaper_form"),), target=False, upgraded_retain=True, pool='necrobinder'),
    define('reave', 'Reave', 1, 'attack', 'common',
           (Attack(), Necro("souls_up", 1),), damage=9, upgraded_damage=11, target=True, pool='necrobinder'),
    define('right_hand_hand', 'Right Hand Hand', 0, 'attack', 'uncommon',
           (OstyAttack(),), damage=4, upgraded_damage=6, target=True, pool='necrobinder'),
    define('sacrifice', 'Sacrifice', 1, 'skill', 'rare',
           (Necro("sacrifice"),), upgraded_cost=0, target=False, retain=True, pool='necrobinder'),
    define('scourge', 'Scourge', 1, 'skill', 'common',
           (Power("doom", 13, 16, target=True), DrawCards(),), draw=1, upgraded_draw=2, target=True, pool='necrobinder'),
    define('sculpting_strike', 'Sculpting Strike', 1, 'attack', 'common',
           (Attack(), Necro("sculpting_strike"),), damage=9, upgraded_damage=12, target=True, strike=True, pool='necrobinder'),
    define('seance', 'Seance', 1, 'skill', 'rare',
           (Necro("seance"),), upgraded_cost=0, target=False, ethereal=True, pool='necrobinder'),
    define('sentry_mode', 'Sentry Mode', 2, 'power', 'rare',
           (Power("sentry_mode"),), upgraded_cost=1, target=False, pool='necrobinder'),
    define('severance', 'Severance', 2, 'attack', 'uncommon',
           (Attack(), Necro("severance"),), damage=13, upgraded_damage=18, target=True, pool='necrobinder'),
    define('shared_fate', 'Shared Fate', 0, 'skill', 'rare',
           (Necro("strength_loss", 2), Necro("enemy_strength_loss", 2, 3),), target=True, exhaust=True, pool='necrobinder'),
    define('shroud', 'Shroud', 1, 'power', 'uncommon',
           (Power("shroud", 2, 3),), block=2, upgraded_block=3, target=False, pool='necrobinder'),
    define('sic_em', 'Sic Em', 1, 'attack', 'uncommon',
           (OstyAttack(), Power("sic_em", 3, 4, target=True),), damage=5, upgraded_damage=6, target=True, pool='necrobinder'),
    define('sleight_of_flesh', 'Sleight Of Flesh', 2, 'power', 'uncommon',
           (Power("sleight_of_flesh", 9, 13),), target=False, pool='necrobinder'),
    define('snap', 'Snap', 1, 'attack', 'common',
           (OstyAttack(), Necro("snap"),), damage=7, upgraded_damage=10, target=True, pool='necrobinder'),
    define('soul_storm', 'Soul Storm', 1, 'attack', 'rare',
           (Attack(expression="exhausted_souls", factor=2, upgraded_factor=3),), damage=9, target=True, pool='necrobinder'),
    define('sow', 'Sow', 1, 'attack', 'common',
           (Attack(all_enemies=True),), damage=8, upgraded_damage=11, target=False, retain=True, pool='necrobinder'),
    define('spirit_of_ash', 'Spirit Of Ash', 1, 'power', 'rare',
           (Power("spirit_of_ash", 4, 5),), target=False, pool='necrobinder'),
    define('spur', 'Spur', 1, 'skill', 'uncommon',
           (Necro("summon", 3, 5), Necro("heal_osty", 5, 7),), target=False, retain=True, pool='necrobinder'),
    define('squeeze', 'Squeeze', 3, 'attack', 'rare',
           (OstyAttack(expression="squeeze"),), damage=25, upgraded_damage=30, target=True, pool='necrobinder'),
    define('strike_necrobinder', 'Strike Necrobinder', 1, 'attack', 'basic',
           (Attack(),), damage=6, upgraded_damage=9, target=True, strike=True, pool='necrobinder'),
    define('the_scythe', 'The Scythe', 2, 'attack', 'rare',
           (Attack(), Necro("scythe", 4, 5),), damage=13, target=True, exhaust=True, pool='necrobinder'),
    define('times_up', 'Times Up', 2, 'attack', 'rare',
           (Attack(expression="doom", factor=1),), damage=0, target=True, exhaust=True, upgraded_retain=True, pool='necrobinder'),
    define('transfigure', 'Transfigure', 1, 'skill', 'rare',
           (Necro("transfigure"),), target=False, exhaust=True, upgraded_exhaust=False, pool='necrobinder'),
    define('undeath', 'Undeath', 0, 'skill', 'rare',
           (GainBlock(), Necro("clone_discard"),), block=7, upgraded_block=9, target=False, pool='necrobinder'),
    define('unleash', 'Unleash', 1, 'attack', 'basic',
           (OstyAttack(expression="unleash"),), damage=6, upgraded_damage=9, target=True, pool='necrobinder'),
    define('veilpiercer', 'Veilpiercer', 1, 'attack', 'uncommon',
           (Attack(), Power("veilpiercer"),), damage=10, upgraded_damage=13, target=True, pool='necrobinder'),
    define('wisp', 'Wisp', 0, 'skill', 'common',
           (Silent("energy", 1),), target=False, exhaust=True, upgraded_retain=True, pool='necrobinder'),
    define('soul', 'Soul', 0, 'skill', 'token',
           (DrawCards(),), draw=2, upgraded_draw=3, target=False, exhaust=True, pool='token'),
    define('sweeping_gaze', 'Sweeping Gaze', 0, 'attack', 'token',
           (OstyAttack(random=True),), damage=10, upgraded_damage=15, target=False, exhaust=True, ethereal=True, pool='token'),
)

ORDINARY_IDS = tuple(d.definition_id for d in DEFINITIONS if d.rarity in ("common", "uncommon", "rare"))
