"""Pinned 0.107.1 solo Regent definitions; values and rules remain explicit."""

from game.headless.cards.builders import define
from game.headless.cards.effects import GainBlock, DrawCards
from game.headless.cards.operations import Attack, Power
from game.headless.cards.silent_effects import Silent
from game.headless.cards.regent_effects import Regent

DEFINITIONS = (
    define('alignment', 'Alignment', 0, 'skill', 'uncommon',
           (Silent("energy", 2, 3),), target=False, star_cost=3, pool='regent'),
    define('arsenal', 'Arsenal', 1, 'power', 'rare',
           (Power("arsenal"),), target=False, innate=True, pool='regent'),
    define('astral_pulse', 'Astral Pulse', 0, 'attack', 'common',
           (Attack(hits=2, all_enemies=True),), damage=6, upgraded_damage=8, target=False, star_cost=3, pool='regent'),
    define('beat_into_shape', 'Beat Into Shape', 1, 'attack', 'rare',
           (Regent("beat_into_shape", 5, 7),), damage=5, upgraded_damage=7, target=True, pool='regent'),
    define('begone', 'Begone', 1, 'skill', 'common',
           (Regent("begone"),), target=False, pool='regent'),
    define('big_bang', 'Big Bang', 0, 'skill', 'rare',
           (DrawCards(), Regent("stars", 1), Silent("energy", 1), Regent("forge", 5),), draw=1, target=False, exhaust=True, innate=True, pool='regent'),
    define('black_hole', 'Black Hole', 1, 'power', 'uncommon',
           (Power("black_hole", 3, 4),), target=False, pool='regent'),
    define('bombardment', 'Bombardment', 3, 'attack', 'rare',
           (Attack(),), damage=18, upgraded_damage=24, target=True, exhaust=True, pool='regent'),
    define('bulwark', 'Bulwark', 2, 'skill', 'uncommon',
           (GainBlock(), Regent("forge", 10, 13),), block=12, upgraded_block=15, target=False, pool='regent'),
    define('bundle_of_joy', 'Bundle Of Joy', 1, 'skill', 'rare',
           (Regent("colorless", 3, 4),), target=False, exhaust=True, pool='regent'),
    define('celestial_might', 'Celestial Might', 2, 'attack', 'common',
           (Attack(hits=3, upgraded_hits=4),), damage=6, target=True, pool='regent'),
    define('charge', 'Charge', 1, 'skill', 'uncommon',
           (Regent("charge", 2),), target=False, pool='regent'),
    define('child_of_the_stars', 'Child Of The Stars', 1, 'power', 'uncommon',
           (Power("child_of_the_stars", 2, 3),), target=False, pool='regent'),
    define('cloak_of_stars', 'Cloak Of Stars', 0, 'skill', 'common',
           (GainBlock(),), block=7, upgraded_block=10, target=False, star_cost=1, pool='regent'),
    define('collision_course', 'Collision Course', 0, 'attack', 'common',
           (Attack(), Regent("debris", 1),), damage=11, upgraded_damage=15, target=True, pool='regent'),
    define('comet', 'Comet', 0, 'attack', 'rare',
           (Attack(), Power("weak", 3, target=True), Power("vulnerable", 3, target=True),), damage=33, upgraded_damage=44, target=True, star_cost=5, pool='regent'),
    define('conqueror', 'Conqueror', 1, 'skill', 'uncommon',
           (Regent("forge", 3, 5), Power("conqueror", target=True),), target=True, pool='regent'),
    define('convergence', 'Convergence', 1, 'skill', 'uncommon',
           (Power("retain_hand"), Power("energy_next_turn"), Power("star_next_turn", 1, 2),), target=False, pool='regent'),
    define('cosmic_indifference', 'Cosmic Indifference', 1, 'skill', 'common',
           (GainBlock(), Regent("cosmic_indifference"),), block=6, upgraded_block=9, target=False, pool='regent'),
    define('crash_landing', 'Crash Landing', 1, 'attack', 'rare',
           (Attack(all_enemies=True), Regent("fill_debris"),), damage=21, upgraded_damage=26, target=False, pool='regent'),
    define('crescent_spear', 'Crescent Spear', 1, 'attack', 'common',
           (Attack(expression="star_cards", factor=2, upgraded_factor=3),), damage=8, target=True, star_cost=1, pool='regent'),
    define('crush_under', 'Crush Under', 1, 'attack', 'common',
           (Attack(all_enemies=True), Regent("area_shackles", 1, 2),), damage=7, upgraded_damage=8, target=False, pool='regent'),
    define('decisions_decisions', 'Decisions Decisions', 0, 'skill', 'rare',
           (DrawCards(), Regent("decisions_decisions"),), draw=3, upgraded_draw=5, target=False, exhaust=True, star_cost=6, pool='regent'),
    define('defend_regent', 'Defend Regent', 1, 'skill', 'basic',
           (GainBlock(),), block=5, upgraded_block=8, target=False, defend=True, pool='regent'),
    define('devastate', 'Devastate', 1, 'attack', 'uncommon',
           (Attack(),), damage=30, upgraded_damage=40, target=True, star_cost=4, pool='regent'),
    define('dying_star', 'Dying Star', 1, 'attack', 'rare',
           (Attack(all_enemies=True), Regent("area_shackles", 9, 11),), damage=9, upgraded_damage=11, target=False, ethereal=True, star_cost=3, pool='regent'),
    define('falling_star', 'Falling Star', 0, 'attack', 'basic',
           (Attack(), Power("weak", target=True), Power("vulnerable", target=True),), damage=8, upgraded_damage=12, target=True, star_cost=2, pool='regent'),
    define('foregone_conclusion', 'Foregone Conclusion', 1, 'skill', 'rare',
           (Power("foregone_conclusion", 2, 3),), target=False, pool='regent'),
    define('furnace', 'Furnace', 1, 'power', 'uncommon',
           (Power("furnace", 5, 7),), target=False, pool='regent'),
    define('gamma_blast', 'Gamma Blast', 0, 'attack', 'uncommon',
           (Attack(), Power("weak", 2, target=True), Power("vulnerable", 2, target=True),), damage=13, upgraded_damage=18, target=True, star_cost=3, pool='regent'),
    define('gather_light', 'Gather Light', 1, 'skill', 'common',
           (GainBlock(), Regent("stars", 1),), block=8, upgraded_block=11, target=False, pool='regent'),
    define('genesis', 'Genesis', 2, 'power', 'rare',
           (Power("genesis", 2, 3),), target=False, pool='regent'),
    define('glimmer', 'Glimmer', 1, 'skill', 'uncommon',
           (DrawCards(), Regent("topdeck"),), draw=3, upgraded_draw=4, target=False, pool='regent'),
    define('glitterstream', 'Glitterstream', 2, 'skill', 'common',
           (Regent("glitterstream", 5, 7),), block=11, upgraded_block=13, target=False, pool='regent'),
    define('glow', 'Glow', 1, 'skill', 'common',
           (Regent("stars", 1, 2), DrawCards(), Power("draw_next_turn"),), draw=1, target=False, pool='regent'),
    define('guards', 'Guards', 2, 'skill', 'rare',
           (Regent("guards"),), target=False, exhaust=True, pool='regent'),
    define('guiding_star', 'Guiding Star', 1, 'attack', 'common',
           (Attack(), DrawCards(),), damage=12, upgraded_damage=13, draw=2, upgraded_draw=3, target=True, star_cost=2, pool='regent'),
    define('heavenly_drill', 'Heavenly Drill', 0, 'attack', 'rare',
           (Attack(hit_expression="heavenly_drill"),), damage=8, upgraded_damage=10, target=True, x=True, pool='regent'),
    define('hegemony', 'Hegemony', 2, 'attack', 'uncommon',
           (Attack(), Power("energy_next_turn", 2, 3),), damage=15, upgraded_damage=18, target=True, pool='regent'),
    define('heirloom_hammer', 'Heirloom Hammer', 2, 'attack', 'rare',
           (Attack(), Regent("heirloom_hammer"),), damage=20, upgraded_damage=25, target=True, pool='regent'),
    define('hidden_cache', 'Hidden Cache', 1, 'skill', 'common',
           (Regent("stars", 1), Power("star_next_turn", 3, 4),), target=False, pool='regent'),
    define('i_am_invincible', 'I Am Invincible', 1, 'skill', 'rare',
           (GainBlock(),), block=10, upgraded_block=13, target=False, pool='regent'),
    define('kingly_kick', 'Kingly Kick', 4, 'attack', 'uncommon',
           (Attack(),), damage=27, upgraded_damage=35, target=True, pool='regent'),
    define('kingly_punch', 'Kingly Punch', 1, 'attack', 'uncommon',
           (Attack(),), damage=8, upgraded_damage=10, target=True, pool='regent'),
    define('knockout_blow', 'Knockout Blow', 3, 'attack', 'uncommon',
           (Regent("knockout_blow", 5),), damage=30, upgraded_damage=38, target=True, pool='regent'),
    define('know_thy_place', 'Know Thy Place', 0, 'skill', 'common',
           (Power("weak", target=True), Power("vulnerable", target=True),), target=True, exhaust=True, upgraded_exhaust=False, pool='regent'),
    define('lunar_blast', 'Lunar Blast', 0, 'attack', 'uncommon',
           (Attack(hit_expression="skills_finished"),), damage=4, upgraded_damage=5, target=True, pool='regent'),
    define('make_it_so', 'Make It So', 0, 'attack', 'rare',
           (Attack(),), damage=6, upgraded_damage=9, target=True, pool='regent'),
    define('manifest_authority', 'Manifest Authority', 1, 'skill', 'uncommon',
           (GainBlock(), Regent("manifest_authority"),), block=7, upgraded_block=8, target=False, pool='regent'),
    define('monarchs_gaze', 'Monarchs Gaze', 2, 'power', 'rare',
           (Power("monarchs_gaze"),), upgraded_cost=1, target=False, pool='regent'),
    define('monologue', 'Monologue', 0, 'skill', 'uncommon',
           (Power("monologue"),), target=False, upgraded_retain=True, pool='regent'),
    define('neutron_aegis', 'Neutron Aegis', 1, 'power', 'rare',
           (Power("plating", 8, 11),), target=False, star_cost=5, pool='regent'),
    define('orbit', 'Orbit', 2, 'power', 'uncommon',
           (Power("orbit"),), upgraded_cost=1, target=False, pool='regent'),
    define('pale_blue_dot', 'Pale Blue Dot', 1, 'power', 'uncommon',
           (Power("pale_blue_dot", 1, 2),), target=False, pool='regent'),
    define('parry', 'Parry', 1, 'power', 'uncommon',
           (Power("parry", 10, 14),), target=False, pool='regent'),
    define('particle_wall', 'Particle Wall', 0, 'skill', 'uncommon',
           (GainBlock(), Regent("return_hand"),), block=9, upgraded_block=12, target=False, star_cost=2, pool='regent'),
    define('patter', 'Patter', 1, 'skill', 'common',
           (GainBlock(), Power("vigor", 2, 3),), block=8, upgraded_block=10, target=False, pool='regent'),
    define('photon_cut', 'Photon Cut', 1, 'attack', 'common',
           (Attack(), DrawCards(), Regent("topdeck"),), damage=10, upgraded_damage=13, draw=1, upgraded_draw=2, target=True, pool='regent'),
    define('pillar_of_creation', 'Pillar Of Creation', 1, 'power', 'uncommon',
           (Power("pillar_of_creation", 3, 4),), block=3, upgraded_block=4, target=False, pool='regent'),
    define('prophesize', 'Prophesize', 2, 'skill', 'uncommon',
           (DrawCards(),), draw=6, upgraded_draw=9, target=False, pool='regent'),
    define('quasar', 'Quasar', 0, 'skill', 'uncommon',
           (Regent("quasar"),), target=False, star_cost=2, pool='regent'),
    define('radiate', 'Radiate', 0, 'attack', 'uncommon',
           (Attack(hit_expression="stars_gained", all_enemies=True),), damage=3, upgraded_damage=4, target=False, pool='regent'),
    define('refine_blade', 'Refine Blade', 1, 'skill', 'common',
           (Regent("forge", 9, 13), Power("energy_next_turn"),), target=False, pool='regent'),
    define('reflect', 'Reflect', 1, 'skill', 'uncommon',
           (GainBlock(), Power("reflect"),), block=15, upgraded_block=20, target=False, star_cost=3, pool='regent'),
    define('resonance', 'Resonance', 1, 'skill', 'uncommon',
           (Power("strength", 1, 2), Regent("area_strength_loss", 1),), target=False, star_cost=3, pool='regent'),
    define('royal_gamble', 'Royal Gamble', 0, 'skill', 'uncommon',
           (Regent("stars", 9),), target=False, exhaust=True, upgraded_retain=True, star_cost=5, pool='regent'),
    define('royalties', 'Royalties', 1, 'power', 'rare',
           (Power("royalties", 30, 40),), target=False, generate=False, pool='regent'),
    define('seeking_edge', 'Seeking Edge', 1, 'power', 'rare',
           (Power("seeking_edge"), Regent("forge", 7, 11),), target=False, pool='regent'),
    define('seven_stars', 'Seven Stars', 2, 'attack', 'rare',
           (Attack(hits=7, all_enemies=True),), damage=7, upgraded_cost=1, target=False, star_cost=7, pool='regent'),
    define('shining_strike', 'Shining Strike', 1, 'attack', 'uncommon',
           (Attack(), Regent("stars", 2), Regent("return_top"),), damage=8, upgraded_damage=11, target=True, strike=True, pool='regent'),
    define('solar_strike', 'Solar Strike', 1, 'attack', 'common',
           (Attack(), Regent("stars", 1, 2),), damage=9, upgraded_damage=10, target=True, strike=True, pool='regent'),
    define('spectrum_shift', 'Spectrum Shift', 2, 'power', 'uncommon',
           (Power("spectrum_shift"),), upgraded_cost=1, target=False, pool='regent'),
    define('spoils_of_battle', 'Spoils Of Battle', 1, 'skill', 'common',
           (Regent("forge", 5, 8), DrawCards(),), draw=2, target=False, pool='regent'),
    define('stardust', 'Stardust', 0, 'attack', 'uncommon',
           (Regent("stardust"),), damage=5, upgraded_damage=7, target=False, star_x=True, pool='regent'),
    define('strike_regent', 'Strike Regent', 1, 'attack', 'basic',
           (Attack(),), damage=6, upgraded_damage=9, target=True, strike=True, pool='regent'),
    define('summon_forth', 'Summon Forth', 1, 'skill', 'uncommon',
           (Regent("summon_forth"), Regent("forge", 8, 11),), target=False, pool='regent'),
    define('supermassive', 'Supermassive', 1, 'attack', 'uncommon',
           (Attack(expression="generated", factor=3, upgraded_factor=4),), damage=5, target=True, pool='regent'),
    define('sword_sage', 'Sword Sage', 2, 'power', 'rare',
           (Power("sword_sage"),), upgraded_cost=1, target=False, pool='regent'),
    define('terraforming', 'Terraforming', 1, 'skill', 'uncommon',
           (Power("vigor", 6, 8),), target=False, pool='regent'),
    define('the_smith', 'The Smith', 1, 'skill', 'rare',
           (Regent("forge", 30, 40),), target=False, star_cost=4, pool='regent'),
    define('tyranny', 'Tyranny', 1, 'power', 'rare',
           (Power("tyranny"),), target=False, innate=True, pool='regent'),
    define('venerate', 'Venerate', 1, 'skill', 'basic',
           (Regent("stars", 2, 3),), target=False, pool='regent'),
    define('void_form', 'Void Form', 3, 'power', 'rare',
           (Power("void_form", 2), Regent("end_turn"),), target=False, ethereal=True, upgraded_ethereal=False, pool='regent'),
    define('wrought_in_war', 'Wrought In War', 1, 'attack', 'common',
           (Attack(), Regent("forge", 7, 9),), damage=7, upgraded_damage=9, target=True, pool='regent'),
    define('sovereign_blade', 'Sovereign Blade', 2, 'attack', 'token',
           (Regent("blade"), Regent("parry"),), damage=10, upgraded_cost=1, target=True, retain=True, pool='token'),
    define('minion_strike', 'Minion Strike', 0, 'attack', 'token',
           (Attack(), DrawCards(),), damage=6, upgraded_damage=9, draw=1, target=True, exhaust=True, strike=True, pool='token'),
    define('minion_dive_bomb', 'Minion Dive Bomb', 0, 'attack', 'token',
           (Attack(),), damage=13, upgraded_damage=16, target=True, exhaust=True, pool='token'),
    define('minion_sacrifice', 'Minion Sacrifice', 0, 'skill', 'token',
           (GainBlock(),), block=8, upgraded_block=11, target=False, exhaust=True, pool='token'),
)

ORDINARY_IDS = tuple(d.definition_id for d in DEFINITIONS if d.rarity in ("common", "uncommon", "rare"))
