"""Pinned 0.107.1 solo Silent content, composed from shared combat commands."""

from game.headless.cards.builders import define
from game.headless.cards.effects import GainBlock, DrawCards, RandomEnemyAttack
from game.headless.cards.operations import Attack, Power
from game.headless.cards.silent_effects import Silent

DEFINITIONS = (
    define("abrasive", "Abrasive", 3, "power", "rare",
           (Power("thorns", 4, 6), Power("dexterity"),), sly=True, target=False, pool="silent"),
    define("accelerant", "Accelerant", 1, "power", "rare",
           (Power("accelerant", 1, 2),), target=False, pool="silent"),
    define("accuracy", "Accuracy", 1, "power", "uncommon",
           (Power("accuracy", 4, 6),), target=False, pool="silent"),
    define("acrobatics", "Acrobatics", 1, "skill", "uncommon",
           (DrawCards(), Silent("discard", 1),), draw=3, upgraded_draw=4, target=False, pool="silent"),
    define("adrenaline", "Adrenaline", 0, "skill", "rare",
           (Silent("energy", 1, 2), DrawCards(),), draw=2, upgraded_draw=2, exhaust=True, target=False, pool="silent"),
    define("afterimage", "Afterimage", 1, "power", "rare",
           (Power("afterimage"),), innate=True, target=False, pool="silent"),
    define("anticipate", "Anticipate", 0, "skill", "common",
           (Silent("anticipate", 2, 3),), target=False, pool="silent"),
    define("assassinate", "Assassinate", 0, "attack", "rare",
           (Attack(), Power("vulnerable", 1, 2, target=True),), damage=10, upgraded_damage=13, exhaust=True, base_innate=True, target=True, pool="silent"),
    define("backflip", "Backflip", 1, "skill", "common",
           (GainBlock(), DrawCards(),), block=5, upgraded_block=8, draw=2, upgraded_draw=2, target=False, pool="silent"),
    define("backstab", "Backstab", 0, "attack", "uncommon",
           (Attack(),), damage=11, upgraded_damage=15, exhaust=True, base_innate=True, target=True, pool="silent"),
    define("blade_of_ink", "Blade Of Ink", 1, "skill", "rare",
           (Silent("inky_shivs", 2, 3),), target=False, pool="silent"),
    define("blade_dance", "Blade Dance", 1, "skill", "common",
           (Silent("shivs", 3, 4),), exhaust=True, target=False, pool="silent"),
    define("blur", "Blur", 1, "skill", "uncommon",
           (GainBlock(), Power("blur"),), block=5, upgraded_block=8, target=False, pool="silent"),
    define("bouncing_flask", "Bouncing Flask", 2, "skill", "uncommon",
           (Silent("bouncing_flask", 3, 4),), target=False, pool="silent"),
    define("bubble_bubble", "Bubble Bubble", 1, "skill", "uncommon",
           (Silent("bubble_bubble", 9, 12),), target=True, pool="silent"),
    define("bullet_time", "Bullet Time", 3, "skill", "rare",
           (Silent("bullet_time"),), upgraded_cost=2, target=False, pool="silent"),
    define("burst", "Burst", 1, "skill", "rare",
           (Power("burst", 1, 2),), target=False, pool="silent"),
    define("calculated_gamble", "Calculated Gamble", 0, "skill", "uncommon",
           (Silent("gamble"),), exhaust=True, upgraded_retain=True, target=False, pool="silent"),
    define("cloak_and_dagger", "Cloak And Dagger", 1, "skill", "common",
           (GainBlock(), Silent("shivs", 1, 2),), block=6, upgraded_block=6, target=False, pool="silent"),
    define("corrosive_wave", "Corrosive Wave", 1, "skill", "rare",
           (Power("corrosive_wave", 2, 3),), target=False, pool="silent"),
    define("dagger_spray", "Dagger Spray", 1, "attack", "common",
           (Attack(hits=2, all_enemies=True),), damage=4, upgraded_damage=6, target=False, pool="silent"),
    define("dagger_throw", "Dagger Throw", 1, "attack", "common",
           (Attack(), DrawCards(), Silent("discard", 1),), draw=1, damage=9, upgraded_damage=12, target=True, pool="silent"),
    define("dash", "Dash", 2, "attack", "uncommon",
           (GainBlock(), Attack(),), damage=10, upgraded_damage=13, block=10, upgraded_block=13, target=True, pool="silent"),
    define("deadly_poison", "Deadly Poison", 1, "skill", "common",
           (Power("poison", 5, 7, target=True),), target=True, pool="silent"),
    define("defend_silent", "Defend Silent", 1, "skill", "basic",
           (GainBlock(),), block=5, upgraded_block=8, target=False, defend=True, pool="silent"),
    define("deflect", "Deflect", 0, "skill", "common",
           (GainBlock(),), block=4, upgraded_block=7, target=False, pool="silent"),
    define("dodge_and_roll", "Dodge And Roll", 1, "skill", "common",
           (Silent("dodge_and_roll"),), block=4, upgraded_block=6, target=False, pool="silent"),
    define("echoing_slash", "Echoing Slash", 1, "attack", "rare",
           (Silent("echoing_slash"),), damage=10, upgraded_damage=13, target=False, pool="silent"),
    define("envenom", "Envenom", 2, "power", "rare",
           (Power("envenom", 1, 2),), target=False, pool="silent"),
    define("escape_plan", "Escape Plan", 0, "skill", "uncommon",
           (Silent("escape_plan", 3, 5),), block=3, upgraded_block=5, target=False, pool="silent"),
    define("expertise", "Expertise", 1, "skill", "uncommon",
           (Silent("expertise", 6, 7),), target=False, pool="silent"),
    define("expose", "Expose", 0, "skill", "uncommon",
           (Silent("expose", 2, 3),), exhaust=True, target=True, pool="silent"),
    define("fan_of_knives", "Fan Of Knives", 2, "power", "rare",
           (Power("fan_of_knives"), Silent("shivs", 4, 5),), target=False, pool="silent"),
    define("finisher", "Finisher", 1, "attack", "uncommon",
           (Attack(hit_expression="attacks_finished"),), damage=6, upgraded_damage=8, target=True, pool="silent"),
    define("flechettes", "Flechettes", 1, "attack", "uncommon",
           (Attack(hit_expression="hand_skills"),), damage=5, upgraded_damage=7, target=True, pool="silent"),
    define("flick_flack", "Flick Flack", 1, "attack", "common",
           (Attack(all_enemies=True),), damage=6, upgraded_damage=8, sly=True, target=False, pool="silent"),
    define("scare", "Scare", 0, "skill", "uncommon",
           (Silent("area_weak", 1),), exhaust=True, upgraded_exhaust=False, target=False, pool="silent"),
    define("footwork", "Footwork", 1, "power", "uncommon",
           (Power("dexterity", 2, 3),), target=False, pool="silent"),
    define("grand_finale", "Grand Finale", 0, "attack", "rare",
           (Attack(all_enemies=True),), damage=60, upgraded_damage=75, target=False, pool="silent"),
    define("hand_trick", "Hand Trick", 1, "skill", "uncommon",
           (GainBlock(), Silent("hand_trick"),), block=7, upgraded_block=10, target=False, pool="silent"),
    define("haze", "Haze", 3, "skill", "uncommon",
           (Silent("area_poison", 4, 6),), sly=True, target=False, pool="silent"),
    define("hidden_daggers", "Hidden Daggers", 0, "skill", "uncommon",
           (Silent("discard", 2), Silent("shivs", 2),), target=False, pool="silent"),
    define("infinite_blades", "Infinite Blades", 1, "power", "uncommon",
           (Power("infinite_blades"),), innate=True, target=False, pool="silent"),
    define("knife_trap", "Knife Trap", 2, "skill", "rare",
           (Silent("knife_trap"),), target=True, pool="silent"),
    define("leading_strike", "Leading Strike", 1, "attack", "common",
           (Attack(), Silent("shivs", 2),), damage=3, upgraded_damage=6, target=True, strike=True, pool="silent"),
    define("leg_sweep", "Leg Sweep", 2, "skill", "uncommon",
           (GainBlock(), Power("weak", 2, 3, target=True),), block=11, upgraded_block=14, target=True, pool="silent"),
    define("malaise", "Malaise", 0, "skill", "rare",
           (Silent("malaise"),), exhaust=True, x=True, target=True, pool="silent"),
    define("master_planner", "Master Planner", 2, "power", "rare",
           (Power("master_planner"),), upgraded_cost=1, target=False, pool="silent"),
    define("memento_mori", "Memento Mori", 1, "attack", "uncommon",
           (Attack(expression="discards", factor=4, upgraded_factor=5),), damage=9, upgraded_damage=11, target=True, pool="silent"),
    define("mirage", "Mirage", 1, "skill", "uncommon",
           (Silent("mirage"),), exhaust=True, upgraded_cost=0, target=False, pool="silent"),
    define("murder", "Murder", 3, "attack", "rare",
           (Attack(expression="draws", factor=1),), damage=1, upgraded_cost=2, target=True, pool="silent"),
    define("neutralize", "Neutralize", 0, "attack", "basic",
           (Attack(), Power("weak", 1, 2, target=True),), damage=3, upgraded_damage=4, target=True, pool="silent"),
    define("nightmare", "Nightmare", 3, "skill", "rare",
           (Silent("nightmare"),), exhaust=True, upgraded_cost=2, target=False, pool="silent"),
    define("noxious_fumes", "Noxious Fumes", 1, "power", "uncommon",
           (Power("noxious_fumes", 2, 3),), target=False, pool="silent"),
    define("outbreak", "Outbreak", 1, "power", "uncommon",
           (Power("outbreak", 11, 15),), target=False, pool="silent"),
    define("phantom_blades", "Phantom Blades", 1, "power", "uncommon",
           (Power("phantom_blades", 9, 12),), target=False, pool="silent"),
    define("piercing_wail", "Piercing Wail", 1, "skill", "common",
           (Silent("area_shackles", 6, 8),), exhaust=True, target=False, pool="silent"),
    define("pinpoint", "Pinpoint", 3, "attack", "uncommon",
           (Attack(),), damage=15, upgraded_damage=19, target=True, pool="silent"),
    define("poisoned_stab", "Poisoned Stab", 1, "attack", "common",
           (Attack(), Power("poison", 3, 4, target=True),), damage=6, upgraded_damage=8, target=True, pool="silent"),
    define("pounce", "Pounce", 2, "attack", "uncommon",
           (Attack(), Power("free_skill"),), damage=14, upgraded_damage=20, target=True, pool="silent"),
    define("precise_cut", "Precise Cut", 0, "attack", "uncommon",
           (Attack(expression="precise"),), damage=13, upgraded_damage=16, target=True, pool="silent"),
    define("predator", "Predator", 2, "attack", "common",
           (Attack(), Power("draw_next_turn", 2),), damage=15, upgraded_damage=20, target=True, pool="silent"),
    define("prepared", "Prepared", 0, "skill", "common",
           (DrawCards(), Silent("discard", 1, 2),), draw=1, upgraded_draw=2, target=False, pool="silent"),
    define("reflex", "Reflex", 3, "skill", "uncommon",
           (DrawCards(),), draw=2, upgraded_draw=3, sly=True, target=False, pool="silent"),
    define("ricochet", "Ricochet", 2, "attack", "common",
           (RandomEnemyAttack(4, 5),), damage=3, upgraded_damage=3, sly=True, target=False, pool="silent"),
    define("serpent_form", "Serpent Form", 3, "power", "rare",
           (Power("serpent_form", 4, 6),), target=False, pool="silent"),
    define("shadow_step", "Shadow Step", 1, "skill", "rare",
           (Silent("discard_all"), Power("shadow_step"),), upgraded_cost=0, target=False, pool="silent"),
    define("shadowmeld", "Shadowmeld", 1, "skill", "rare",
           (Power("shadowmeld"),), upgraded_cost=0, target=False, pool="silent"),
    define("skewer", "Skewer", 0, "attack", "uncommon",
           (Attack(hit_expression="x"),), damage=8, upgraded_damage=11, x=True, target=True, pool="silent"),
    define("slice", "Slice", 0, "attack", "common",
           (Attack(),), damage=6, upgraded_damage=9, target=True, pool="silent"),
    define("snakebite", "Snakebite", 2, "skill", "common",
           (Power("poison", 7, 10, target=True),), retain=True, target=True, pool="silent"),
    define("speedster", "Speedster", 2, "power", "uncommon",
           (Power("speedster", 2),), innate=True, target=False, pool="silent"),
    define("storm_of_steel", "Storm Of Steel", 1, "skill", "rare",
           (Silent("storm_of_steel"),), target=False, pool="silent"),
    define("strangle", "Strangle", 1, "attack", "uncommon",
           (Attack(), Power("strangle", 2, 3, target=True),), damage=8, upgraded_damage=10, target=True, pool="silent"),
    define("strike_silent", "Strike Silent", 1, "attack", "basic",
           (Attack(),), damage=6, upgraded_damage=9, target=True, strike=True, pool="silent"),
    define("sucker_punch", "Sucker Punch", 1, "attack", "common",
           (Attack(), Power("weak", 1, 2, target=True),), damage=8, upgraded_damage=10, target=True, pool="silent"),
    define("survivor", "Survivor", 1, "skill", "basic",
           (GainBlock(), Silent("discard", 1),), block=8, upgraded_block=11, target=False, pool="silent"),
    define("tactician", "Tactician", 3, "skill", "uncommon",
           (Silent("energy", 1, 2),), sly=True, target=False, pool="silent"),
    define("the_hunt", "The Hunt", 1, "attack", "rare",
           (Silent("the_hunt"),), damage=10, upgraded_damage=15, exhaust=True, target=True, generate=False, pool="silent"),
    define("tools_of_the_trade", "Tools Of The Trade", 1, "power", "rare",
           (Power("tools_of_the_trade"),), upgraded_cost=0, target=False, pool="silent"),
    define("tracking", "Tracking", 2, "power", "rare",
           (Power("tracking"),), upgraded_cost=1, target=False, pool="silent"),
    define("untouchable", "Untouchable", 2, "skill", "common",
           (GainBlock(),), block=6, upgraded_block=9, sly=True, target=False, pool="silent"),
    define("up_my_sleeve", "Up My Sleeve", 2, "skill", "uncommon",
           (Silent("shivs", 3, 4), Silent("cheaper"),), target=False, pool="silent"),
    define("well_laid_plans", "Well Laid Plans", 1, "power", "uncommon",
           (Power("well_laid_plans", 1, 2),), target=False, pool="silent"),
    define("shiv", "Shiv", 0, "attack", "token",
           (Silent("shiv"),), damage=4, upgraded_damage=6, exhaust=True, target=True, pool="token"),
)

ORDINARY_IDS = tuple(d.definition_id for d in DEFINITIONS if d.rarity in ("common", "uncommon", "rare"))
